Repository openshift/cluster-image-registry-operator, pull requests merged in 2018-11, with the labels that each got.

#50 Use global config to bootstrap gcs driver
  pkg/clusterconfig/clusterconfig.go
  pkg/operator/bootstrap.go
  pkg/operator/handler.go
  pkg/resource/podtemplatespec.go
  pkg/resource/service.go
  pkg/storage/azure/azure.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
Labels: approved, lgtm, size/L

#53 Cluster-scoped image resource
  cmd/cluster-image-registry-operator/main.go
  deploy/00-crd.yaml
  pkg/clusteroperator/clusteroperator.go
  pkg/metautil/humanname.go
  pkg/operator/finalizer.go
  pkg/operator/handler.go
  pkg/resource/podtemplatespec.go
  pkg/resource/state.go
Labels: approved, lgtm, size/M

#55 dockerfile for running e2e tests
  Dockerfile.e2e
Labels: approved, lgtm, size/XS

#56 introduce a minimal e2e test that confirms the registry operator came up
  test/e2e/cluster_image_registry_operator_test.go
  test/e2e/main_test.go
  test/e2e/s3_test.go
Labels: approved, lgtm, size/M

#57 remove unneeded dockerfile e2e
  Dockerfile.e2e
Labels: approved, lgtm

#60 pkg/clusterconfig: Log missing config-map
  pkg/clusterconfig/clusterconfig.go
Labels: approved, lgtm, size/XS

#62 make tests wait for the operator
  Makefile
  test/e2e/cluster_image_registry_operator_test.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/M

#65 Register kind Route for decoder
  cmd/cluster-image-registry-operator/main.go
Labels: approved, lgtm, size/XS

#64 Adapt DCs with deprecated environment variables
  pkg/migration/migration.go
  pkg/migration/testdata/openshift-default-registry/deploymentconfig.yaml
  pkg/migration/testdata/openshift-default-registry/imageregistryspec.yaml
Labels: approved, lgtm, size/M

#69 Refactoring
  cmd/cluster-image-registry-operator/main.go
  pkg/apis/imageregistry/v1alpha1/types.go
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  pkg/operator/handler.go
  pkg/operator/routes.go
  pkg/operator/status.go
  pkg/parameters/parameters.go
  pkg/resource/apply.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/configmap.go
  pkg/resource/deployment.go
  pkg/resource/deploymentconfig.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/podtemplatespec.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
  pkg/resource/state.go
  pkg/resource/template.go
  pkg/resource/types.go
  pkg/signals/signal.go
  pkg/storage/azure/azure.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/consts.go
Labels: approved, lgtm, size/XXL

#71 Make private most of resource functions
  cmd/cluster-image-registry-operator/main.go
  pkg/client/client.go
  pkg/clusterconfig/clusterconfig.go
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  pkg/resource/apply.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/configmap.go
  pkg/resource/deployment.go
  pkg/resource/deploymentconfig.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/podtemplatespec.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
  pkg/resource/strategy/configmap.go
  pkg/resource/strategy/deployment.go
  pkg/resource/strategy/deploymentconfig.go
  pkg/resource/strategy/imageconfig.go
  pkg/resource/strategy/interface.go
  pkg/resource/strategy/override.go
  pkg/resource/strategy/secret.go
  pkg/resource/strategy/service.go
  pkg/resource/template.go
Labels: approved, lgtm, size/XL

#72 add temporary hack to copy service ca to cluster nodes
  Dockerfile
  Dockerfile.rhel7
  deploy/05-ca-config.yaml
  deploy/06-ca-rbac.yaml
  deploy/07-ca-serviceaccount.yaml
  deploy/08-ca-daemonset.yaml
Labels: approved, lgtm, size/L

#70 Update status logic
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  pkg/operator/status.go
Labels: approved, lgtm, size/L

#52 Updating S3 configuration completion
  pkg/clusterconfig/clusterconfig.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/util/consts.go
  pkg/storage/util/util.go
  pkg/util/util.go
  test/e2e/aws_test.go
  test/e2e/consts.go
  test/e2e/main_test.go
  test/e2e/util.go
Labels: approved, lgtm, size/XL

#80 tmp directory should not contain non-temporary information
  Makefile
  hack/build/Dockerfile
  hack/build/build.sh
  hack/build/docker_build.sh
  hack/codegen/boilerplate.go.txt
  hack/codegen/update-generated.sh
Labels: approved, lgtm, size/S

#82 tagging s3 bucket with cluster id
  Makefile
  pkg/storage/s3/s3.go
  test/e2e/aws_test.go
  test/e2e/s3_test.go
Labels: approved, lgtm, size/M

#84 Set user tags on s3 bucket
  pkg/storage/s3/s3.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/M

#87 Rollback from k8s.io/klog to github.com/golang/glog
  cmd/cluster-image-registry-operator/main.go
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/operator/controller/clusterrolebindings/clusterrolebindings.go
  pkg/operator/controller/clusterroles/clusterroles.go
  pkg/operator/controller/configmaps/configmap.go
  pkg/operator/controller/deployments/deployment.go
  pkg/operator/controller/imageregistry/imageregistry.go
  pkg/operator/controller/routes/routes.go
  pkg/operator/controller/secrets/secret.go
  pkg/operator/controller/serviceaccounts/serviceaccounts.go
  pkg/operator/controller/services/service.go
  pkg/operator/finalizer.go
  pkg/operator/status.go
  pkg/resource/generator.go
  pkg/storage/storage.go
  pkg/storage/util/util.go
Labels: approved, lgtm, size/L

#90 create config namespaces as part of image registry operator bringup
  deploy/01-openshift-config-managed-namespace.yaml
  deploy/01-openshift-config-namespace.yaml
Labels: approved, lgtm, size/S

#88 bump(*)
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/apimachinery/pkg/api/meta/patch_priority.go
  vendor/k8s.io/apimachinery/pkg/api/meta/priority.go
  vendor/k8s.io/apimachinery/pkg/api/meta/restmapper.go
  vendor/k8s.io/apimachinery/pkg/api/meta/testrestmapper/patch_restmapper.go
  vendor/k8s.io/apimachinery/pkg/api/testing/codec.go
  vendor/k8s.io/apimachinery/pkg/runtime/error.go
  vendor/k8s.io/apimachinery/pkg/runtime/scheme.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json_patch.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json_test.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning_test.go
  vendor/k8s.io/apimachinery/pkg/util/diff/diff.go
  vendor/k8s.io/apimachinery/pkg/util/diff/diff_test.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/intstr_test.go
  vendor/k8s.io/apimachinery/pkg/util/naming/from_stack.go
  vendor/k8s.io/apimachinery/pkg/util/naming/from_stack_test.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/client-go/Godeps/Godeps.json
  vendor/k8s.io/client-go/discovery/round_tripper.go
  vendor/k8s.io/client-go/discovery/unstructured.go
  vendor/k8s.io/client-go/kubernetes/typed/authorization/v1/fake/fake_subjectaccessreview_expansion.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/scale/client.go
  vendor/k8s.io/client-go/scale/patch_dc.go
  vendor/k8s.io/client-go/tools/cache/fifo.go
  vendor/k8s.io/client-go/tools/cache/fifo_test.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config_test.go
  vendor/k8s.io/client-go/tools/clientcmd/config.go
  vendor/k8s.io/client-go/tools/clientcmd/loader.go
  vendor/k8s.io/client-go/tools/clientcmd/loader_test.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/client-go/util/certificate/certificate_manager.go
  vendor/k8s.io/client-go/util/certificate/certificate_manager_test.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/generic.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/packages.go
  vendor/k8s.io/code-generator/cmd/lister-gen/generators/lister.go
Labels: approved, lgtm

#83 remove operator sdk makefile invocation
  Makefile
Labels: approved, lgtm, retest-not-required, size/XS

#86 Set Status.ManagedStorage on the registry operator custom resource
  pkg/apis/imageregistry/v1alpha1/types.go
  pkg/clusterconfig/clusterconfig.go
  pkg/operator/bootstrap.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/M

#92 Recreate CR when it is deleted
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/operator/finalizer.go
Labels: approved, lgtm, size/M

#97 add docs
  README.md
Labels: approved, lgtm, size/L

#101 add pod priorities
  deploy/04-operator.yaml
  deploy/08-ca-daemonset.yaml
Labels: approved, lgtm, retest-not-required

#103 Bootstrap with enabled TLS and info logs
  pkg/operator/bootstrap.go
Labels: approved, lgtm, size/XS

#98 Add tests for Failing status and for basic logs
  deploy/05-ca-config.yaml
  pkg/operator/complete.go
  pkg/operator/controller.go
  pkg/testframework/imageregistry.go
  pkg/testframework/logs.go
  test/e2e/basic_empty_dir_test.go
  test/e2e/failing_test.go
  test/e2e/recreate_deployment_test.go
Labels: approved, lgtm, size/L
