Repository openshift/cluster-image-registry-operator, pull requests merged in 2018-10, with the labels that each got.

#26 Watch for all the necessary resources and re-create them if necessary
  cmd/cluster-image-registry-operator/main.go
  pkg/generate/apply.go
  pkg/generate/clusterrole.go
  pkg/generate/clusterrolebinding.go
  pkg/generate/configmap.go
  pkg/generate/deployment.go
  pkg/generate/deploymentconfig.go
  pkg/generate/podtemplatespec.go
  pkg/generate/route.go
  pkg/generate/secret.go
  pkg/generate/service.go
  pkg/operator/bootstrap.go
  pkg/operator/complete.go
  pkg/operator/handler.go
  pkg/operator/routes.go
  pkg/parameters/parameters.go
Labels: approved, lgtm, size/L

#27 Use RBAC from k8s.io
  cmd/cluster-image-registry-operator/main.go
  deploy/02-rbac.yaml
  pkg/generate/clusterrole.go
  pkg/generate/clusterrolebinding.go
  pkg/operator/handler.go
Labels: approved, lgtm, size/M

#28 Add REGISTRY_OPENSHIFT_SERVER_ADDR
  pkg/generate/podtemplatespec.go
Labels: approved, lgtm, size/XS

#31 Add finalizer
  deploy/cr.yaml
  pkg/operator/bootstrap.go
  pkg/operator/complete.go
  pkg/operator/finalizer.go
  pkg/operator/handler.go
  pkg/parameters/parameters.go
Labels: approved, lgtm, size/L

#35 Prohibit the change of storage subtype
  pkg/generate/route.go
  pkg/operator/bootstrap.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/storage.go
Labels: approved, lgtm, size/M

#36 Create image-registry deployment by default
  pkg/operator/handler.go
Labels: approved, lgtm, size/XS

#37 deploy the registry operator and registry on the master
  deploy/04-operator.yaml
  pkg/apis/imageregistry/v1alpha1/types.go
  pkg/apis/imageregistry/v1alpha1/zz_generated.deepcopy.go
  pkg/generate/podtemplatespec.go
Labels: approved, lgtm, size/S

#41 get the image-registry image name from the cluster env
  deploy/04-operator.yaml
  deploy/image-references
  pkg/generate/podtemplatespec.go
  pkg/operator/bootstrap.go
  pkg/operator/handler.go
Labels: approved, lgtm, size/S

#44 Update image-registry status based on deployment status
  cmd/cluster-image-registry-operator/main.go
  pkg/operator/handler.go
Labels: approved, lgtm, size/L

#46 Refactoring
  pkg/clusterconfig/clusterconfig.go
  pkg/clusteroperator/clusteroperator.go
  pkg/operator/finalizer.go
  pkg/operator/handler.go
  pkg/operator/routes.go
  pkg/resource/apply.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/configmap.go
  pkg/resource/deployment.go
  pkg/resource/deploymentconfig.go
  pkg/resource/imageconfig.go
  pkg/resource/podtemplatespec.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
  pkg/resource/state.go
  pkg/resource/template.go
  pkg/resource/types.go
  pkg/resource/utils.go
Labels: approved, lgtm, size/L

#49 remove master node selector
  deploy/04-operator.yaml
  pkg/resource/podtemplatespec.go
Labels: approved, lgtm, size/XS
