Repository openshift/cluster-image-registry-operator, pull requests merged in 2018-12, with the labels that each got.

#105 Fix test
  test/e2e/failing_test.go
Labels: approved, lgtm, size/XS

#102 Fix conditions and error handling
  pkg/operator/controller.go
  pkg/operator/status.go
Labels: approved, lgtm, size/L

#95 A few cleanup items
  cmd/cluster-image-registry-operator/main.go
  pkg/clusterconfig/clusterconfig.go
  pkg/operator/controller.go
  pkg/operator/controller/imageregistry/imageregistry.go
  pkg/operator/controller/routes/routes.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/M

#108 Add test for Unmanaged state
  pkg/operator/status.go
  pkg/testframework/imageregistry.go
  test/e2e/aws_test.go
  test/e2e/unmanaged_test.go
Labels: approved, lgtm, size/L

#107 Store configuration struct in status
  pkg/apis/imageregistry/v1alpha1/types.go
  pkg/apis/imageregistry/v1alpha1/zz_generated.deepcopy.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/M

#110 use short hostname for registry
  deploy/08-ca-daemonset.yaml
  pkg/operator/controller.go
Labels: approved, lgtm, size/XS

#113 Set default encryption on S3 bucket and update bucket name
  pkg/storage/s3/s3.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/S

#112 Copy CAs from openshift-config namespace
  deploy/02-rbac.yaml
  pkg/apis/imageregistry/v1alpha1/types.go
  pkg/client/listers.go
  pkg/metautil/humanname.go
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/operator/controller/clusterrolebindings/clusterrolebindings.go
  pkg/operator/controller/clusterroles/clusterroles.go
  pkg/operator/controller/configmaps/configmap.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/deployments/deployment.go
  pkg/operator/controller/imageregistry/imageregistry.go
  pkg/operator/controller/routes/routes.go
  pkg/operator/controller/secrets/secret.go
  pkg/operator/controller/serviceaccounts/serviceaccounts.go
  pkg/operator/controller/services/service.go
  pkg/operator/finalizer.go
  pkg/operator/status.go
  pkg/operator/util.go
  pkg/parameters/parameters.go
  pkg/resource/caconfig.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/configmap.go
  pkg/resource/dependencies.go
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/podtemplatespec.go
  pkg/resource/resource.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
  pkg/resource/strategy/checksum.go
  pkg/resource/strategy/configmap.go
  pkg/resource/strategy/deployment.go
  pkg/resource/strategy/deploymentconfig.go
  pkg/resource/strategy/imageconfig.go
  pkg/resource/strategy/interface.go
  pkg/resource/strategy/metadata.go
  pkg/resource/strategy/override.go
  pkg/resource/strategy/override_test.go
  pkg/resource/strategy/secret.go
  pkg/resource/strategy/service.go
  pkg/resource/template.go
  test/e2e/basic_empty_dir_test.go
Labels: approved, lgtm, size/XXL

#114 replace tectonicClusterID tag with openshiftClusterID
  pkg/storage/s3/s3.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/XS

#116 Use cr.Spec.Proxy.HTTP and cr.Spec.Proxy.HTTPS
  pkg/resource/podtemplatespec.go
Labels: approved, lgtm, size/XS

#117 Always handle events from watchers
  pkg/operator/controller.go
Labels: approved, lgtm, size/S

#118 use a status subresource for the image config api
  deploy/00-crd.yaml
  deploy/02-rbac.yaml
  deploy/04-operator.yaml
  pkg/resource/imageconfig.go
  pkg/testframework/imageregistry.go
  test/e2e/aws_test.go
  test/e2e/basic_empty_dir_test.go
Labels: approved, lgtm, size/M

#119 Add CR.Spec.Proxy.NoProxy
  pkg/apis/imageregistry/v1alpha1/types.go
  pkg/resource/podtemplatespec.go
Labels: approved, lgtm, size/S

#121 fix comment that still refers to tectonicClusterID
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/XS

#122 A few small cleanup items
  pkg/clusterconfig/clusterconfig.go
  pkg/operator/controller.go
  pkg/resource/strategy/override_test.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/S

#123 update clusteroperator status properly and add rbac permission to do so
  deploy/02-rbac.yaml
  pkg/clusteroperator/clusteroperator.go
  pkg/testframework/imageregistry.go
  test/e2e/aws_test.go
  test/e2e/basic_empty_dir_test.go
Labels: approved, lgtm, size/M

#127 Use Cluster Version ClusterID instead of Install Config ClusterID
  deploy/02-rbac.yaml
  pkg/storage/s3/s3.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/M
