Repository openshift/cluster-image-registry-operator, pull requests merged in 2018-09, with the labels that each got.

#1 setup installer manifest content
  .gitignore
  Dockerfile
  Makefile
  deploy/image-references
  deploy/operator.yaml
  pkg/parameters/parameters.go
Labels: approved, lgtm, size/M

#2 Fix case
  deploy/image-references
Labels: approved, lgtm, size/XS

#3 fix hack script to use makefile to build
  hack/deploy.sh
Labels: approved, lgtm, size/XS

#6 Prepare repo for distgit conventions
  cluster-image-registry-operator.spec
Labels: approved, lgtm, size/L

#7 Revert "Prepare repo for distgit conventions"
  cluster-image-registry-operator.spec
Labels: approved, lgtm, size/L

#8 deploy: add ordering to manifests that end up in updatepayload
  Dockerfile
  deploy/00-crd.yaml
  deploy/01-namespace.yaml
  deploy/02-rbac.yaml
  deploy/03-operator.yaml
  hack/deploy.sh
Labels: approved, lgtm, size/S

#10 Revert "Revert "deploy: add ordering to manifests that end up in updatepayload""
  Dockerfile
  deploy/00-crd.yaml
  deploy/01-namespace.yaml
  deploy/02-rbac.yaml
  deploy/03-operator.yaml
  hack/deploy.sh
Labels: approved, lgtm, size/S

#13 Save immutable config parameters into configmap
  Dockerfile-dev
  pkg/generate/deployment.go
  pkg/generate/deploymentconfig.go
  pkg/generate/podtemplatespec.go
  pkg/generate/state.go
  pkg/operator/handler.go
  pkg/parameters/parameters.go
  pkg/storage/azure/azure.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
Labels: approved, lgtm, size/L

#15 Generate new bucket name if it already exists
  pkg/storage/gcs/gcs.go
Labels: approved, lgtm, size/S

#19 Log resource name on condition failure
  pkg/operator/handler.go
Labels: approved, lgtm, size/XS

#20 Split template generation and apply
  pkg/operator/handler.go
Labels: approved, lgtm, size/M

#21 Rename custom resource to ImageRegistry
  cmd/cluster-image-registry-operator/main.go
  config/config.yaml
  deploy/00-crd.yaml
  deploy/02-rbac.yaml
  deploy/cr.yaml
  pkg/apis/dockerregistry/v1alpha1/doc.go
  pkg/apis/dockerregistry/v1alpha1/types.go
  pkg/apis/dockerregistry/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/imageregistry/v1alpha1/doc.go
  pkg/apis/imageregistry/v1alpha1/register.go
  pkg/apis/imageregistry/v1alpha1/types.go
  pkg/apis/imageregistry/v1alpha1/zz_generated.deepcopy.go
  pkg/generate/clusterrole.go
  pkg/generate/clusterrolebinding.go
  pkg/generate/configmap.go
  pkg/generate/deployment.go
  pkg/generate/deploymentconfig.go
  pkg/generate/podtemplatespec.go
  pkg/generate/route.go
  pkg/generate/secret.go
  pkg/generate/service.go
  pkg/generate/serviceaccount.go
  pkg/generate/state.go
  pkg/generate/types.go
  pkg/generate/utils.go
  pkg/operator/bootstrap.go
  pkg/operator/complete.go
  pkg/operator/handler.go
  pkg/operator/routes.go
  pkg/parameters/parameters.go
  pkg/storage/azure/azure.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  tmp/codegen/update-generated.sh
Labels: approved, lgtm, size/XL

#22 Remove checksum calculation
  pkg/generate/podtemplatespec.go
  pkg/operator/handler.go
  pkg/parameters/parameters.go
Labels: approved, lgtm, size/M

#23 Improve registry operator
  cmd/cluster-image-registry-operator/main.go
  pkg/generate/apply.go
  pkg/generate/clusterrole.go
  pkg/generate/clusterrolebinding.go
  pkg/generate/configmap.go
  pkg/generate/route.go
  pkg/generate/secret.go
  pkg/generate/service.go
  pkg/generate/serviceaccount.go
  pkg/generate/state.go
  pkg/generate/utils.go
  pkg/operator/bootstrap.go
  pkg/operator/complete.go
  pkg/operator/handler.go
Labels: approved, lgtm, size/L

#24 deploy: add namespace for the CR.
  deploy/cr.yaml
Labels: approved, lgtm, size/XS

#25 don't include cr in manifests
  Dockerfile
Labels: approved, lgtm, size/XS
