Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-01, with the labels that each got.

#129 Abort incomplete multipart uploads on AWS/S3
  pkg/apis/imageregistry/v1alpha1/types.go
  pkg/storage/s3/s3.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/L

#132 a small refactor / cleanup
  pkg/clusterconfig/clusterconfig.go
  pkg/operator/finalizer.go
  pkg/resource/generator.go
  pkg/storage/s3/s3.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  test/e2e/util.go
Labels: approved, lgtm, size/M

#133 be more judicious when setting modified=true
  pkg/operator/bootstrap.go
  pkg/operator/finalizer.go
  pkg/resource/caconfig.go
  pkg/resource/generator.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/L

#136 initialize configlistener field
  pkg/resource/caconfig.go
Labels: approved, lgtm, size/S

#131 Update to openshift/api/v1 deps
  Gopkg.lock
  Gopkg.toml
  pkg/apis/imageregistry/v1/types.go
  pkg/apis/imageregistry/v1/zz_generated.deepcopy.go
  pkg/migration/migration.go
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/operator/status.go
  pkg/resource/podtemplatespec.go
  pkg/storage/s3/s3.go
  pkg/storage/util/util.go
  pkg/testframework/imageregistry.go
  test/e2e/aws_test.go
  test/e2e/basic_empty_dir_test.go
  test/e2e/failing_test.go
  test/e2e/recreate_deployment_test.go
  test/e2e/unmanaged_test.go
  test/e2e/util.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#139 Make the node CA daemonset only run on Linux using a nodeselector
  pkg/resource/nodecadaemon.go
Labels: approved, lgtm, size/XS

#137 Refactoring the S3 storage driver
  pkg/apis/imageregistry/v1/types.go
  pkg/apis/imageregistry/v1/zz_generated.deepcopy.go
  pkg/operator/finalizer.go
  pkg/resource/generator.go
  pkg/resource/nodecadaemon.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/testframework/framework.go
  test/e2e/aws_test.go
  test/e2e/unmanaged_test.go
Labels: approved, lgtm, size/L

#143 Renaming the image registry resource
  deploy/00-crd.yaml
  deploy/cr.yaml
  hack/codegen/update-generated.sh
  pkg/apis/imageregistry/v1/register.go
  pkg/apis/imageregistry/v1/types.go
  pkg/apis/imageregistry/v1/zz_generated.deepcopy.go
  pkg/client/listers.go
  pkg/clusterconfig/clusterconfig.go
  pkg/generated/clientset/versioned/typed/imageregistry/v1/config.go
  pkg/generated/clientset/versioned/typed/imageregistry/v1/fake/fake_config.go
  pkg/generated/clientset/versioned/typed/imageregistry/v1/fake/fake_imageregistry.go
  pkg/generated/clientset/versioned/typed/imageregistry/v1/fake/fake_imageregistry_client.go
  pkg/generated/clientset/versioned/typed/imageregistry/v1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/imageregistry/v1/imageregistry.go
  pkg/generated/clientset/versioned/typed/imageregistry/v1/imageregistry_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/imageregistry/v1/config.go
  pkg/generated/informers/externalversions/imageregistry/v1/interface.go
  pkg/generated/listers/imageregistry/v1/config.go
  pkg/generated/listers/imageregistry/v1/expansion_generated.go
  pkg/generated/listers/imageregistry/v1/imageregistry.go
  pkg/operator/bootstrap.go
  pkg/operator/complete.go
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  pkg/operator/status.go
  pkg/resource/caconfig.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/nodecadaemon.go
  pkg/resource/podtemplatespec.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
  pkg/resource/strategy/override_test.go
  pkg/resource/utils.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  pkg/testframework/imageregistry.go
  test/e2e/aws_test.go
  test/e2e/basic_empty_dir_test.go
  test/e2e/failing_test.go
  test/e2e/recreate_deployment_test.go
  test/e2e/unmanaged_test.go
  test/e2e/util.go
Labels: approved, lgtm, size/XXL

#146 Add support for syncing registry certs
  pkg/resource/nodecadaemon.go
Labels: approved, lgtm, size/S

#147 Cleanup Items
  Makefile
  pkg/clusterconfig/clusterconfig.go
  pkg/migration/migration.go
  pkg/migration/migration_test.go
  pkg/operator/bootstrap.go
  pkg/operator/complete.go
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  pkg/operator/status.go
  pkg/resource/caconfig.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/nodecadaemon.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
  pkg/resource/strategy/override_test.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  pkg/testframework/framework.go
  pkg/testframework/imageregistry.go
  test/e2e/aws_test.go
  test/e2e/basic_empty_dir_test.go
  test/e2e/failing_test.go
  test/e2e/recreate_deployment_test.go
  test/e2e/unmanaged_test.go
  test/e2e/util.go
Labels: approved, lgtm, size/XL

#149 skip driver.CompleteConfiguration if the driver is nil
  pkg/operator/bootstrap.go
  pkg/resource/generator.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/s3/s3.go
  pkg/testframework/framework.go
Labels: approved, lgtm, size/M

#153 drop tls api
  README.md
  pkg/apis/imageregistry/v1/types.go
  pkg/migration/migration.go
  pkg/operator/bootstrap.go
  pkg/resource/podtemplatespec.go
  pkg/resource/route.go
  pkg/resource/service.go
Labels: approved, lgtm, size/L

#155 Typo fix
  pkg/client/client.go
Labels: approved, lgtm, size/XS

#158 don't create default route unless it is requested
  pkg/resource/generator.go
Labels: approved, lgtm, size/XS

#162 Do not encrypt the bucket if we did not create it
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/L

#163 Set operator cpu request
  deploy/04-operator.yaml
Labels: approved, lgtm, size/XS

#164 Remove storage medium if ManagementState set to Removed
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  pkg/resource/generator.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/util/util.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/L

#159 set external registry hostnames on cluster image config
  pkg/apis/imageregistry/v1/types.go
  pkg/operator/complete.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/testframework/clientset.go
  test/e2e/configuration_test.go
Labels: approved, size/L

#167 Use cloud credentials secret
  pkg/clusterconfig/clusterconfig.go
Labels: approved, lgtm, size/S

#172 Check for NoSuchBucket when deleting a bucket
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/M

#171 make e2e tests more flake tolerant
  pkg/testframework/imageregistry.go
  pkg/testframework/operator.go
Labels: approved, lgtm, size/M

#170 Create secret before deployment
  pkg/clusterconfig/clusterconfig.go
  pkg/operator/bootstrap.go
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/podtemplatespec.go
  pkg/resource/secret.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/L

#176 better error reporting on failed secret retrieval
  pkg/clusterconfig/clusterconfig.go
Labels: approved, lgtm, size/S

#179 various fixes
  pkg/resource/generator.go
Labels: approved, lgtm, size/S

#181 use newly created object for update invocation
  pkg/resource/imageconfig.go
Labels: approved, lgtm, size/S

#182 Allow registry to use imagestreams/layers
  pkg/resource/clusterrole.go
Labels: approved, lgtm, size/XS

#156 Update Get calls to use the lister cache
  pkg/client/listers.go
  pkg/clusterconfig/clusterconfig.go
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  pkg/resource/generator.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  pkg/testframework/mock/listers/listers.go
  pkg/testframework/mock/listers/secrets.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/L
