Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-04, with the labels that each got.

#252 Fix e2e tests
  Makefile
  test/framework/operator.go
Labels: approved, lgtm, size/XS

#248 Show false values in config's spec
  pkg/apis/imageregistry/v1/types.go
Labels: approved, lgtm, size/M

#249 fix config resource name in readme
  README.md
Labels: approved, lgtm, size/XS

#255 Fix PVC access mode validation
  pkg/storage/pvc/pvc.go
Labels: approved, lgtm, size/S

#257 Remove unsupported storages
  pkg/apis/imageregistry/v1/types.go
  pkg/apis/imageregistry/v1/zz_generated.deepcopy.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/storage.go
  test/e2e/configuration_test.go
  test/e2e/emptydir_test.go
  test/e2e/failing_test.go
  test/e2e/readonly_test.go
  test/e2e/recreate_deployment_test.go
  test/e2e/unmanaged_test.go
Labels: approved, lgtm, size/XL

#253 Use generator for ClusterOperator
  manifests/02-rbac.yaml
  pkg/client/listers.go
  pkg/clusteroperator/clusteroperator.go
  pkg/operator/controller.go
  pkg/operator/status.go
  pkg/resource/caconfig.go
  pkg/resource/clusteroperator.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/nodecadaemon.go
  pkg/resource/object/diff.go
  pkg/resource/object/dump.go
  pkg/resource/resource.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
  test/framework/logs.go
Labels: approved, lgtm, size/XL

#262 Restore Swift in newDriver
  pkg/storage/storage.go
Labels: approved, lgtm, size/XS

#266 Add node-selector annotation to namespace
  manifests/01-namespace.yaml
  manifests/01-openshift-config-managed-namespace.yaml
  manifests/01-openshift-config-namespace.yaml
Labels: lgtm, size/XS

#268 Document credentials flow for AWS
  docs/Makefile
  docs/aws-creds.dot
  docs/aws-creds.png
  docs/credentials-flow.md
Labels: approved, lgtm, size/M

#269 Removing openshift-config namespaces from manifest
  manifests/01-openshift-config-managed-namespace.yaml
  manifests/01-openshift-config-namespace.yaml
Labels: approved, lgtm, size/S
