Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-12, with the labels that each got.

#417 Bug 1769008: Bumping openshift/api.
  go.mod
  go.sum
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#419 Use junit_*.xml pattern for junit reports
  hack/test-go.sh
Labels: approved, lgtm, size/XS

#418 Bug 1784208: force path style for custom endpoints
  pkg/storage/s3/s3.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
