Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-10, with the labels that each got.

#395 Remove CGO_ENABLED=0 from build script
  hack/build/build.sh
Labels: approved, lgtm, size/XS

#387 Bug 1753778: report Available when registry is explicitly Removed
  pkg/operator/status.go
  test/e2e/managementstate_test.go
  test/e2e/unmanaged_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#394 Bug 1722878: reseting configured storages before DeepCopy()
  pkg/resource/generator.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/gcs/gcs.go
  pkg/storage/pvc/pvc.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#398 Implementing test for storage swap.
  test/e2e/imageconfig_test.go
Labels: approved, lgtm, size/M

#385 Bug 1756475: Add flag 'DisableRedirect', decide to route all data through the registry
  manifests/00-crd.yaml
  pkg/apis/imageregistry/v1/types.go
  pkg/resource/podtemplatespec.go
  test/e2e/configuration_test.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/M

#368 DEVEXP-404: Added implementation for operator metrics/alerts.
  cmd/cluster-image-registry-operator/main.go
  manifests/0000_90_cluster-image-registry-operator_02_operator-servicemonitor.yaml
  manifests/07-operator-service.yaml
  manifests/07-operator.yaml
  manifests/09-prometheus-rules.yaml
  pkg/metrics/metrics.go
  pkg/metrics/server.go
  pkg/metrics/server_test.go
  pkg/operator/status.go
  pkg/resource/generator.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/gcs/gcs.go
  pkg/storage/pvc/pvc.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
Labels: approved, lgtm, size/L

#402 DEVEX-404: Part 2 - Removing redundant metrics.
  manifests/09-prometheus-rules.yaml
  pkg/metrics/metrics.go
  pkg/metrics/server.go
  pkg/metrics/server_test.go
  pkg/operator/status.go
Labels: approved, lgtm, size/L

#399 [4.2] Bug 1759159: Reset storage when swapping back end type
  pkg/resource/generator.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/gcs/gcs.go
  pkg/storage/pvc/pvc.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  test/e2e/imageconfig_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#392 DEVEXP-419: Bootstrapping operator as Removed on BareMetal.
  Makefile
  manifests/09-prometheus-rules.yaml
  pkg/operator/bootstrap.go
  pkg/resource/clusteroperator.go
  pkg/resource/generator.go
  pkg/storage/storage.go
  test/e2e/baremetal_test.go
  test/e2e/managementstate_test.go
Labels: approved, lgtm, size/L
