Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-07, with the labels that each got.

#309 No proxy configured if proxy/cluster does not exist
  pkg/operator/controller.go
Labels: approved, lgtm, size/XS

#315 Bug 1727595: Warn on missing proxy config instead of error
  pkg/operator/controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#316 Bug 1727595: Fix error on proxy config not found
  pkg/operator/controller.go
  pkg/resource/podtemplatespec.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#308 Refactor to get rid of clusterconfig/clusterconfig.go
  manifests/02-rbac.yaml
  pkg/apis/imageregistry/v1/types.go
  pkg/client/listers.go
  pkg/clusterconfig/clusterconfig.go
  pkg/operator/controller.go
  pkg/storage/azure/azure.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  test/e2e/baremetal_test.go
  test/framework/mock/listers/infrastructure.go
  test/framework/mock/listers/listers.go
  test/framework/mock/listers/secrets.go
Labels: approved, lgtm, size/XL

#304 Add OpenStack credentials request manifest
  manifests/01-registry-credentials-request-openstack.yaml
Labels: approved, lgtm, size/S

#306 Add test for route secrets
  test/e2e/configuration_test.go
Labels: approved, lgtm, size/L

#320 Bug 1729714: cluster-config-v1 is a config map
  pkg/client/listers.go
  pkg/operator/controller.go
  pkg/storage/util/util.go
  test/framework/mock/listers/configmaps.go
  test/framework/mock/listers/listers.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#323 [openstack] Allow custom cloud names
  Gopkg.lock
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/register.go
  vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  vendor/github.com/openshift/api/console/v1/types_console_link.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#321 [release-4.1] Bug 1730407: add test for route secrets
  test/e2e/configuration_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#326 OpenStack: do not set empty env variables
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, size/M

#325 OpenStack: tolerate incorrect urls with double / in the path
  Gopkg.lock
  Gopkg.toml
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
  vendor/github.com/PuerkitoBio/purell/.gitignore
  vendor/github.com/PuerkitoBio/purell/.travis.yml
  vendor/github.com/PuerkitoBio/purell/LICENSE
  vendor/github.com/PuerkitoBio/purell/README.md
  vendor/github.com/PuerkitoBio/purell/bench_test.go
  vendor/github.com/PuerkitoBio/purell/benchmarks/v0.1.0
  vendor/github.com/PuerkitoBio/purell/example_test.go
  vendor/github.com/PuerkitoBio/purell/purell.go
  vendor/github.com/PuerkitoBio/purell/purell_test.go
  vendor/github.com/PuerkitoBio/purell/urlnorm_test.go
  vendor/github.com/PuerkitoBio/urlesc/.travis.yml
  vendor/github.com/PuerkitoBio/urlesc/LICENSE
  vendor/github.com/PuerkitoBio/urlesc/README.md
  vendor/github.com/PuerkitoBio/urlesc/urlesc.go
  vendor/github.com/PuerkitoBio/urlesc/urlesc_test.go
  vendor/github.com/goware/urlx/.travis.yml
  vendor/github.com/goware/urlx/LICENSE
  vendor/github.com/goware/urlx/README.md
  vendor/github.com/goware/urlx/go.mod
  vendor/github.com/goware/urlx/go.sum
  vendor/github.com/goware/urlx/urlx.go
  vendor/github.com/goware/urlx/urlx_test.go
Labels: approved, lgtm, size/XXL

#328 correcting gcp credentials request
  manifests/01-registry-credentials-request-gcs.yaml
Labels: approved, lgtm, size/XS

#329 dedeuplicate swift test code
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, size/L

#335 change serviceaccount.json to service_account.json
  pkg/storage/gcs/gcs.go
Labels: approved, lgtm, size/XS

#338 Add scope to gcs credentials
  pkg/storage/gcs/gcs.go
Labels: approved, lgtm, size/XS

#334 Bug 1733902: Retry container creation on correct ServiceCode
  pkg/storage/azure/azure.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#336 Don't use a global variable for the s3 service
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/S

#339 Update GCS bucket creation
  pkg/storage/gcs/gcs.go
Labels: approved, lgtm, size/S

#341 Bug 1711173: Handle emptying the s3 bucket before deleting it
  pkg/storage/s3/s3.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
