Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-03, with the labels that each got.

#226 test/e2e: Do not wait for PVC to change its status from "Pending" to something else
  test/e2e/pvc_test.go
Labels: approved, lgtm, size/S

#227 Add adambkaplan as approver
  OWNERS
Labels: approved, lgtm, size/XS

#229 Fix namespace for errors for installer-cloud-credentials
  pkg/clusterconfig/clusterconfig.go
Labels: approved, lgtm, size/XS

#225 operator: Report cluster operator version as per the new standard
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
  pkg/apis/imageregistry/v1/types.go
  pkg/clusteroperator/clusteroperator.go
  pkg/operator/finalizer.go
  pkg/operator/status.go
  pkg/resource/deployment.go
  test/e2e/configuration_test.go
  test/framework/cvo.go
  test/framework/imageregistry.go
  test/framework/operator.go
Labels: approved, lgtm, size/L

#230 resource: specify system-cluster-critical priority for registry
  pkg/resource/podtemplatespec.go
Labels: approved, lgtm, size/XS

#233 manifests: update image pull policy
  manifests/07-operator.yaml
Labels: approved, lgtm, size/XS

#236 Add LICENSE file
  LICENSE
  README.md
Labels: approved, lgtm, size/L

#235 add missing s3 endpoint
  pkg/storage/s3/s3.go
Labels: approved, lgtm, ok-to-test, size/XS

#237 openstack: add domain and tenant config
  pkg/apis/imageregistry/v1/types.go
  pkg/storage/swift/swift.go
Labels: approved, lgtm, ok-to-test, size/S

#234 [4.1] Add cloudfront support
  pkg/apis/imageregistry/v1/types.go
  pkg/apis/imageregistry/v1/zz_generated.deepcopy.go
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/M

#238 Update region from the install config if not present
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/XS

#240 Re-enable TestAWSUnableToCreateBucketOnStartup
  test/e2e/aws_test.go
Labels: approved, lgtm, size/XS

#239 Add ability to set tolerations for registry pod
  pkg/apis/imageregistry/v1/types.go
  pkg/apis/imageregistry/v1/zz_generated.deepcopy.go
  pkg/resource/podtemplatespec.go
  test/e2e/configuration_test.go
Labels: approved, lgtm, size/M

#244 fix up owners files
  OWNERS
Labels: approved, lgtm, size/XS

#243 update credentialsrequest from v1beta1 to v1
  manifests/01-registry-credentials-request.yaml
Labels: approved, lgtm, size/XS

#242 Do not configure PVC by default
  pkg/storage/storage.go
Labels: approved, lgtm, size/XS

#241 add anti affinity to docker registry pods
  pkg/resource/podtemplatespec.go
Labels: approved, lgtm, size/S

#245 api: Replace time.Duration by metav1.Duration
  pkg/apis/imageregistry/v1/types.go
  pkg/apis/imageregistry/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XS

#246 Add reasons to conditions
  pkg/clusteroperator/clusteroperator.go
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  pkg/operator/status.go
  pkg/resource/generator.go
  test/e2e/baremetal_test.go
  test/framework/imageregistry.go
Labels: approved, lgtm, size/L

#247 Add must-gather object refs
  pkg/clusteroperator/clusteroperator.go
  pkg/operator/controller.go
  pkg/resource/caconfig.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/nodecadaemon.go
  pkg/resource/resource.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
Labels: approved, lgtm, size/L
