Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-02, with the labels that each got.

#183 Remove CRD for images.config.openshift.io
  deploy/00-crd.yaml
Labels: approved, lgtm, size/S

#184 remove unnecessary status.internalregistryhostname field
  pkg/apis/imageregistry/v1/types.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/operator/controller.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/nodecadaemon.go
  pkg/testframework/imageregistry.go
Labels: approved, lgtm, size/L

#187 Refactoring bootstrap.go to only look for one custom resource
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
Labels: approved, lgtm, size/L

#188 Reorganizing some of the testframework
  test/e2e/aws_test.go
  test/e2e/configuration_test.go
  test/e2e/emptydir_test.go
  test/e2e/failing_test.go
  test/e2e/main_test.go
  test/e2e/recreate_deployment_test.go
  test/e2e/unmanaged_test.go
  test/framework/clientset.go
  test/framework/condition.go
  test/framework/cvo.go
  test/framework/framework.go
  test/framework/hostname.go
  test/framework/imageregistry.go
  test/framework/logs.go
  test/framework/mock/listers/listers.go
  test/framework/mock/listers/secrets.go
  test/framework/operator.go
  test/framework/route.go
Labels: approved, lgtm, size/L

#191 A few more cleanup items
  hack/build/build.sh
  pkg/apis/imageregistry/v1/register.go
  pkg/client/client.go
  pkg/migration/dependency/namespacedresources.go
  pkg/migration/migration.go
  pkg/operator/complete.go
  pkg/operator/controller.go
  pkg/resource/podtemplatespec.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/M

#189 rename registry clusteroperator resource plus file renames+cleanup
  Dockerfile
  Dockerfile.rhel7
  config/config.yaml
  manifests/00-crd.yaml
  manifests/0000_90_cluster-image-registry-operator_00_servicemonitor-rbac.yaml
  manifests/0000_90_cluster-image-registry-operator_01_operand-servicemonitor.yaml
  manifests/01-namespace.yaml
  manifests/01-openshift-config-managed-namespace.yaml
  manifests/01-openshift-config-namespace.yaml
  manifests/02-rbac.yaml
  manifests/03-sa.yaml
  manifests/04-ca-config.yaml
  manifests/05-ca-rbac.yaml
  manifests/06-ca-serviceaccount.yaml
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
  manifests/image-references
  manifests/registry-config.yaml
  pkg/apis/imageregistry/v1/types.go
  pkg/client/client.go
  pkg/operator/controller.go
  test/framework/imageregistry.go
Labels: approved, lgtm, size/M

#166 Initial plumbing to support Encrypt, and KeyID (KMS Encryption)
  pkg/apis/imageregistry/v1/types.go
  pkg/storage/s3/s3.go
  test/e2e/aws_test.go
  test/framework/hostname.go
Labels: approved, lgtm, size/L

#196 Use AdditionalTrustedCA from image config
  pkg/apis/imageregistry/v1/types.go
  pkg/resource/caconfig.go
  pkg/resource/generator.go
Labels: approved, lgtm, size/S

#199 add credential request for aws
  manifests/01-registry-credentials-request.yaml
Labels: approved, lgtm, size/M

#198 update nodeca image spec if image payload changes
  pkg/resource/nodecadaemon.go
Labels: approved, lgtm, size/XS

#192 Remove modified
  pkg/operator/bootstrap.go
  pkg/operator/complete.go
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  pkg/operator/status.go
  pkg/resource/generator.go
  pkg/resource/strategy/metadata.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/filesystem/filesystem.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  test/e2e/emptydir_test.go
Labels: approved, lgtm, size/L

#201 Renaming image registry resource
  manifests/registry-config.yaml
  pkg/apis/imageregistry/v1/types.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/XS

#207 check deployment memory, not pod to avoid looking at a stale pod
  test/e2e/configuration_test.go
Labels: approved, lgtm, size/S

#203 avoid a potential nilptr error during logging
  pkg/operator/controller.go
Labels: approved, lgtm, size/XS

#202 openstack: Add temporary OpenStack suport on FS
  pkg/storage/storage.go
Labels: approved, lgtm, size/XS

#174 Add PVC storage driver
  pkg/apis/imageregistry/v1/types.go
  pkg/apis/imageregistry/v1/zz_generated.deepcopy.go
  pkg/resource/caconfig.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
  pkg/resource/utils.go
  pkg/storage/pvc/pvc.go
  pkg/storage/storage.go
  pkg/util/util.go
  test/e2e/configuration_test.go
  test/e2e/pvc_test.go
  test/framework/clientset.go
  test/framework/framework.go
  test/framework/imageregistry.go
Labels: approved, lgtm, size/XL

#209 Enable subresource status
  manifests/00-crd.yaml
  pkg/operator/controller.go
Labels: approved, lgtm, size/M

#210 Add ReadOnly flag
  pkg/apis/imageregistry/v1/types.go
  pkg/resource/podtemplatespec.go
  test/e2e/readonly_test.go
Labels: approved, lgtm, size/M

#215 do not setup ownerrefs for clusterscoped/cross-namespace objects
  Makefile
  pkg/resource/caconfig.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/nodecadaemon.go
  pkg/resource/resource.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
  pkg/storage/pvc/pvc.go
Labels: approved, lgtm, size/L

#212 s3: include operator version in UserAgent for AWS API calls
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/XS

#222 disable kube/openshift api server operators before running tests
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/nodecadaemon.go
  pkg/storage/pvc/pvc.go
  pkg/util/util.go
  test/e2e/aws_test.go
  test/e2e/main_test.go
  test/e2e/pvc_test.go
  test/framework/cvo.go
  test/framework/imageregistry.go
  test/framework/operator.go
Labels: approved, lgtm, size/L

#224 Return error that happened
  pkg/clusterconfig/clusterconfig.go
Labels: approved, lgtm, size/XS
