Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-09, with the labels that each got.

#383 Bug 1748436: Add namespace to related objects
  pkg/resource/clusteroperator.go
  test/framework/imageregistry.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#382 Bug 1745811: Making sure we don't have a sequence of dashes.
  pkg/storage/util/util.go
  pkg/storage/util/util_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#377 Bug 1738475: Update condition reason code for invalid keyID
  pkg/storage/gcs/gcs.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#378 Bug 1740035: Azure should create custom container
  pkg/storage/azure/azure.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#386 Bug 1752916: add config resource to relatedObjects
  pkg/resource/clusteroperator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
