Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-08, with the labels that each got.

#337 Use context.Background() for Azure
  pkg/storage/azure/azure.go
  pkg/storage/gcs/gcs.go
  pkg/storage/storage.go
Labels: approved, lgtm, size/M

#346 Do not hardcode GOOS/GOARCH
  hack/build/build.sh
Labels: approved, lgtm, ok-to-test, size/XS

#344 Use context for aws
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
Labels: approved, lgtm, size/S

#333 Refactor client creation/usage
  pkg/client/clients.go
  pkg/operator/controller.go
  pkg/resource/generator.go
Labels: approved, lgtm, size/L

#345 Use annotation to request proxy configuration injection from the cvo
  manifests/07-operator.yaml
  pkg/operator/controller.go
  test/e2e/configuration_test.go
  test/framework/deployment.go
  test/framework/operator.go
Labels: approved, lgtm, size/L

#351 Bug 1737526: Empty s3 bucket before deleting
  pkg/storage/s3/s3.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#352 Add Name tag to S3 bucket
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/XS

#353 Start storage name with cluster name
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/XS

#347 OpenStack: set container metadata
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, size/M

#348 adding gosec to make verify
  Makefile
  hack/verify-gofmt.sh
Labels: approved, lgtm, size/S

#354 Bug 1726894: Properly setting "maxWaitTime" environment var.
  pkg/resource/podtemplatespec.go
  test/e2e/configuration_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#350 Bug 1737053: Fixing error 409 container name exists
  pkg/storage/azure/azure.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#343 Bug 1734564: Remove Service CA ConfigMap from CVO management
  manifests/04-ca-config.yaml
  test/e2e/aws_test.go
  test/framework/configmap.go
  test/framework/daemonset.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#362 Updating name of container to inject proxy information into
  manifests/07-operator.yaml
Labels: approved, lgtm, size/XS

#366 Bug 1738475: Bucket is nil if already exists during update
  pkg/storage/gcs/gcs.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#355 Use common generateName for storage
  pkg/storage/azure/azure.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
  pkg/storage/util/util.go
  pkg/storage/util/util_test.go
Labels: approved, lgtm, size/L

#365 Removed Dockerfile.rhel7.
  Dockerfile.rhel7
Labels: approved, lgtm, size/S

#357 [release-4.1] Bug 1714168: Properly setting "maxWaitTime" environment…
  pkg/resource/podtemplatespec.go
  test/e2e/configuration_test.go
  test/framework/util.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#367 Set default role for minted credentials to Contributor
  manifests/01-registry-credentials-request-azure.yaml
Labels: approved, lgtm, size/XS

#340 DEVEXP-403: Mount cluster trusted CA to image registry operator
  manifests/04-ca-trusted.yaml
  manifests/07-operator.yaml
Labels: approved, lgtm, size/S

#370 Removed CA volume mount from watch container.
  manifests/07-operator.yaml
Labels: approved, lgtm, size/XS

#371 Bug 1740370: don't use DeploymentNotFound when storage is not configured
  pkg/operator/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#360 DEVEXP-402: Mount trusted-ca to registry base pki trust source
  pkg/client/fake/fixtures.go
  pkg/operator/controller.go
  pkg/parameters/parameters.go
  pkg/resource/podtemplatespec.go
  pkg/resource/podtemplatespec_test.go
Labels: approved, lgtm, size/L

#369 Don't set global proxy status manually
  test/e2e/configuration_test.go
  test/e2e/gcs_test.go
  test/framework/imageregistry.go
  test/framework/proxy.go
  test/framework/util.go
Labels: approved, lgtm, size/M

#374 DEVEXP-403: Using hard link when creating watcher binary.
  Dockerfile
Labels: approved, lgtm, size/XS

#379 Overwrite CA trust bundle only on 4.2 clusters
  Dockerfile
  images/bin/entrypoint.sh
  manifests/07-operator.yaml
Labels: approved, lgtm, size/S

#376 Bug 1746155: Revert mount of trusted CA bundle
  manifests/07-operator.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#372 Bug 1710502: Using trap to deal with signaling on node-ca.
  pkg/resource/nodecadaemon.go
  test/e2e/graceful_shutdown_test.go
  test/framework/logs.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
