Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-05, with the labels that each got.

#272 Bug 1703941: use image-registry-certificates for system and user certificates
  pkg/operator/controller.go
  pkg/parameters/parameters.go
  pkg/resource/caconfig.go
  pkg/resource/dependencies.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  pkg/resource/nodecadaemon.go
  pkg/resource/serviceca.go
  test/e2e/imageconfig_test.go
Labels: approved, lgtm, size/L

#275 Fix tolerations
  manifests/07-operator.yaml
Labels: approved, lgtm, size/XS

#276 Add azure platform support, with emptydir as storage backend
  pkg/storage/storage.go
Labels: approved, lgtm, size/S

#274 Apply ClusterOperator even if everything is bad
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/operator/status.go
  pkg/resource/clusteroperator.go
  pkg/resource/generator.go
  test/e2e/aws_test.go
  test/e2e/baremetal_test.go
  test/e2e/configuration_test.go
  test/e2e/emptydir_test.go
  test/e2e/pvc_test.go
  test/e2e/readonly_test.go
  test/framework/imageregistry.go
Labels: approved, lgtm, size/L

#278 Remove legionus as reviewer/approver
  OWNERS
Labels: approved, lgtm, size/XS

#281 pkg: add resource requests to node-ca pod
  pkg/resource/nodecadaemon.go
Labels: approved, lgtm, size/XS

#280 Add GCS support for UPI installs
  CONTRIBUTING.md
  pkg/apis/imageregistry/v1/types.go
  pkg/apis/imageregistry/v1/zz_generated.deepcopy.go
  pkg/clusterconfig/clusterconfig.go
  pkg/storage/gcs/gcs.go
  pkg/storage/storage.go
  test/e2e/gcs_test.go
Labels: approved, lgtm, size/L

#283 Remove CompleteConfiguration
  pkg/operator/bootstrap.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/pvc/pvc.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
Labels: approved, lgtm, size/M

#284 Updates to the GCS configuration and documentation
  README.md
  pkg/clusterconfig/clusterconfig.go
  pkg/storage/gcs/gcs.go
  test/e2e/gcs_test.go
Labels: approved, lgtm, size/S

#285 Temporarily switch OpenStack to EmptyDir
  pkg/storage/storage.go
Labels: approved, lgtm, size/XS

#287 Fix a typo in the documentation
  docs/aws-creds.dot
  docs/aws-creds.png
Labels: approved, lgtm, size/XS

#288 Swift: fallback to "object-store" endpoint type
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, size/M

#289 Cleanup
  README.md
  pkg/clusterconfig/clusterconfig.go
  pkg/coreutil/doc.go
  pkg/coreutil/volumesource.go
  pkg/coreutil/volumesource_test.go
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  pkg/operator/objectinfo.go
  pkg/resource/generator.go
  pkg/storage/pvc/pvc.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  test/e2e/gcs_test.go
  test/framework/secret.go
Labels: approved, lgtm, size/L
