Repository openshift/cluster-image-registry-operator, pull requests merged in 2019-06, with the labels that each got.

#292 Revert "Temporarily switch OpenStack to EmptyDir"
  pkg/storage/storage.go
Labels: approved, lgtm, size/XS

#295 OpenStack: generate different container names
  cmd/cluster-image-registry-operator/main.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, size/S

#296 use GA kubelet OS label
  pkg/resource/nodecadaemon.go
Labels: approved, lgtm, size/XS

#299 Bug 1719965: fix handling TLS secrets for routes
  pkg/resource/route.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#302 OpenStack: allow to explicitly specify keystone auth version
  manifests/00-crd.yaml
  pkg/apis/imageregistry/v1/types.go
  pkg/clusterconfig/clusterconfig.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, size/L

#305 Block public access to S3 bucket and its objects by default
  manifests/01-registry-credentials-request.yaml
  pkg/apis/imageregistry/v1/types.go
  pkg/storage/s3/s3.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/M
