Repository openshift/cluster-image-registry-operator, pull requests merged in 2020-04, with the labels that each got.

#510 Using random name for PVC during tests
  go.mod
  test/e2e/pvc_test.go
Labels: approved, lgtm

#509 Bug 1809245: Try to attach to all pods during test
  test/e2e/graceful_shutdown_test.go
  test/framework/daemonset.go
  test/framework/logs.go
Labels: approved, bugzilla/valid-bug, lgtm

#508 Wait until operator is rolled out after its deployment is changed
  test/e2e/configuration_test.go
  test/framework/cvo.go
  test/framework/deployment.go
  test/framework/imageregistry.go
  test/framework/operator.go
Labels: approved, lgtm

#514 Prefix Azure storage account name with "imageregistry"
  pkg/storage/azure/azure.go
Labels: approved, lgtm

#507 Bug 1807471: add always-on controller for image-registry-certificates
  pkg/defaults/defaults.go
  pkg/operator/controller.go
  pkg/operator/imageregistrycertificates.go
  pkg/operator/nodecadaemon.go
  pkg/resource/caconfig.go
  pkg/resource/generator.go
  test/e2e/configuration_test.go
  test/e2e/graceful_shutdown_test.go
  test/e2e/nodecadaemon_test.go
  test/e2e/recreate_deployment_test.go
  test/framework/daemonset.go
  test/framework/deployment.go
  test/framework/framework.go
  test/framework/imageregistry.go
  test/framework/proxy.go
Labels: approved, bugzilla/valid-bug, lgtm

#512 [release-4.4] Bug 1810562: bootstrap HA configuration
  pkg/operator/bootstrap.go
  pkg/resource/generator.go
  pkg/storage/storage.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#517 fix error message typo
  pkg/operator/controllerimagepruner.go
Labels: approved, lgtm

#515 Bug 1821427: Giving Image Config resource its own controller
  pkg/operator/controller.go
  pkg/operator/imageconfig.go
  pkg/resource/caconfig.go
  pkg/resource/generator.go
  pkg/resource/imageconfig.go
  test/e2e/imageconfig_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#502 [release-4.4] Bug 1808425: ignore most kube-system events
  go.mod
  pkg/client/fake/fixtures.go
  pkg/client/listers.go
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/storage/azure/azure.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  test/e2e/gcs_test.go
  test/framework/mock/listers/listers.go
  vendor/github.com/openshift/installer/LICENSE
  vendor/github.com/openshift/installer/NOTICE
  vendor/github.com/openshift/installer/pkg/ipnet/ipnet.go
  vendor/github.com/openshift/installer/pkg/types/aws/doc.go
  vendor/github.com/openshift/installer/pkg/types/aws/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/aws/metadata.go
  vendor/github.com/openshift/installer/pkg/types/aws/platform.go
  vendor/github.com/openshift/installer/pkg/types/azure/doc.go
  vendor/github.com/openshift/installer/pkg/types/azure/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/azure/metadata.go
  vendor/github.com/openshift/installer/pkg/types/azure/platform.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/OWNERS
  vendor/github.com/openshift/installer/pkg/types/baremetal/doc.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/metadata.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/platform.go
  vendor/github.com/openshift/installer/pkg/types/clustermetadata.go
  vendor/github.com/openshift/installer/pkg/types/doc.go
  vendor/github.com/openshift/installer/pkg/types/gcp/clouduid.go
  vendor/github.com/openshift/installer/pkg/types/gcp/doc.go
  vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/gcp/metadata.go
  vendor/github.com/openshift/installer/pkg/types/gcp/platform.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/installconfig_libvirt.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/OWNERS
  vendor/github.com/openshift/installer/pkg/types/libvirt/doc.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/metadata.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/network.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/platform.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/none/doc.go
  vendor/github.com/openshift/installer/pkg/types/none/platform.go
  vendor/github.com/openshift/installer/pkg/types/openstack/OWNERS
  vendor/github.com/openshift/installer/pkg/types/openstack/doc.go
  vendor/github.com/openshift/installer/pkg/types/openstack/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/openstack/metadata.go
  vendor/github.com/openshift/installer/pkg/types/openstack/platform.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/OWNERS
  vendor/github.com/openshift/installer/pkg/types/vsphere/doc.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/platform.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#513 Add component to OWNERS
  OWNERS
Labels: approved, lgtm

#520 DEVEXP-368: get S3 endpoint from infrastructure status
  go.mod
  go.sum
  pkg/client/clients.go
  pkg/operator/bootstrap.go
  pkg/operator/bootstrap_test.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_scheduler.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/fake/doc.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/fake/fake_config.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/fake/fake_imagepruner.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/fake/fake_imageregistry_client.go
  vendor/modules.txt
Labels: approved, lgtm

#503 [release-4.3] Bug 1808426: ignore most kube-system events
  pkg/client/fake/fixtures.go
  pkg/client/listers.go
  pkg/operator/controller.go
  pkg/storage/azure/azure.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#511 [4.3] Bug 1820242: nodeca daemon should tolerate all taints
  pkg/resource/nodecadaemon.go
  pkg/resource/nodecadaemon_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#504 [release-4.3] Bug 1816656: update ClusterOperator object even if operator is unmanaged
  pkg/operator/bootstrap.go
  pkg/operator/clusteroperator.go
  pkg/operator/controller.go
  pkg/resource/clusteroperator.go
  pkg/resource/clusteroperator_test.go
  pkg/resource/generator.go
  test/e2e/baremetal_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#522 bindata: Run node-ca as hostNetwork to avoid NetworkNotReady
  bindata/nodecadaemon.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm

#527 Bug 1825165: update object dumper
  pkg/resource/object/diff.go
  pkg/resource/object/diff_test.go
  pkg/resource/object/dump.go
  pkg/resource/object/dump_test.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#523 [release-4.4] Bug 1826033: Bootstrap as suspended
  pkg/operator/controllerimagepruner.go
  test/e2e/pruner_test.go
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#526 Bug 1828719: Retry updating config resource during tests.
  test/e2e/managementstate_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#539 Bug 1827807: Assure storage bucket names in lowercase
  pkg/storage/util/util.go
  pkg/storage/util/util_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#543 Bug 1829910: fail the test when required objects are not found
  test/e2e/pruner_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
