Repository openshift/cluster-image-registry-operator, pull requests merged in 2020-01, with the labels that each got.

#423 Remove Gopkg files
  Gopkg.lock
  Gopkg.toml
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#421 Bug 1785115: tolerate all NoSchedule taints
  pkg/resource/nodecadaemon.go
  pkg/resource/nodecadaemon_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#425 Use dual stack endpoints for S3
  pkg/storage/s3/s3.go
Labels: approved, lgtm, size/XS

#430 bump(api,client-go):
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/register.go
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_csi_snapshot.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imagepruner.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imageregistry_client.go
  vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/imageregistry/v1/imagepruner.go
  vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/imageregistry/v1/interface.go
  vendor/github.com/openshift/client-go/imageregistry/listers/imageregistry/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/imageregistry/listers/imageregistry/v1/imagepruner.go
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#431 Revert "Merge pull request #430 from adambkaplan/bump-api-clientgo"
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/register.go
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_csi_snapshot.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imagepruner.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imageregistry_client.go
  vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/imageregistry/v1/imagepruner.go
  vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/imageregistry/v1/interface.go
  vendor/github.com/openshift/client-go/imageregistry/listers/imageregistry/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/imageregistry/listers/imageregistry/v1/imagepruner.go
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#432 bump(api,client-go)
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/register.go
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_csi_snapshot.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imagepruner.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imageregistry_client.go
  vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/imageregistry/v1/imagepruner.go
  vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/imageregistry/v1/interface.go
  vendor/github.com/openshift/client-go/imageregistry/listers/imageregistry/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/imageregistry/listers/imageregistry/v1/imagepruner.go
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#420 Encode environment variables as YAML
  pkg/envvar/envvar.go
  pkg/envvar/envvar_test.go
  pkg/resource/podtemplatespec.go
  pkg/resource/secret.go
  pkg/storage/azure/azure.go
  pkg/storage/emptydir/emptydir.go
  pkg/storage/gcs/gcs.go
  pkg/storage/pvc/pvc.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, size/XL

#435 removing verify-sec / gosec
  Makefile
Labels: approved, lgtm, size/XS

#436 Use bindata for nodecadaemon
  Makefile
  bindata/nodecadaemon.yaml
  go.mod
  go.sum
  manifests/registry-config.yaml
  pkg/assets/bindata.go
  pkg/resource/nodecadaemon.go
  tools.go
  vendor/github.com/jteeuwen/go-bindata/CONTRIBUTING.md
  vendor/github.com/jteeuwen/go-bindata/LICENSE
  vendor/github.com/jteeuwen/go-bindata/Makefile
  vendor/github.com/jteeuwen/go-bindata/README.md
  vendor/github.com/jteeuwen/go-bindata/asset.go
  vendor/github.com/jteeuwen/go-bindata/bytewriter.go
  vendor/github.com/jteeuwen/go-bindata/config.go
  vendor/github.com/jteeuwen/go-bindata/convert.go
  vendor/github.com/jteeuwen/go-bindata/debug.go
  vendor/github.com/jteeuwen/go-bindata/doc.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/main.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/version.go
  vendor/github.com/jteeuwen/go-bindata/release.go
  vendor/github.com/jteeuwen/go-bindata/restore.go
  vendor/github.com/jteeuwen/go-bindata/stringwriter.go
  vendor/github.com/jteeuwen/go-bindata/toc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/codegen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-glide.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/images.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/yq.mk
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#428 Start using rolloutStrategy parameter
  pkg/operator/bootstrap.go
  pkg/resource/deployment.go
  test/e2e/configuration_test.go
Labels: approved, lgtm, size/M

#439 DEVEXP-523: Allow to use RWO access mode for PVC storage type
  pkg/storage/pvc/pvc.go
  test/e2e/pvc_test.go
Labels: approved, lgtm, size/M

#440 Add retries to route tests
  test/e2e/configuration_test.go
Labels: approved, lgtm, size/S

#438 Bug 1791281: Swift authVersion should be integer
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#442 Check for errors in defer
  test/e2e/configuration_test.go
  test/framework/framework.go
  test/framework/proxy.go
Labels: approved, lgtm, size/S

#441 Swiftless OpenStack
  defaults/defaults.go
  pkg/operator/bootstrap.go
  pkg/storage/pvc/pvc.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, size/L

#443 Dump related resources when DeployImageRegistry fails
  test/framework/imageregistry.go
Labels: approved, lgtm, size/XS

#444 Fix lint warnings
  pkg/resource/object/diff.go
  pkg/resource/podtemplatespec.go
  pkg/storage/azure/azure.go
  pkg/storage/gcs/gcs.go
  pkg/storage/pvc/pvc.go
Labels: approved, lgtm, size/M

#427 DEVEXP-433: Report image pruner's install status in Prometheus
  manifests/09-prometheus-rules.yaml
  pkg/metrics/metrics.go
  pkg/metrics/server.go
  pkg/metrics/server_test.go
  pkg/resource/generator.go
Labels: approved, lgtm, size/M

#434 DEVEXP-497: enable dualstack endpoints for S3
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  pkg/storage/storage.go
  test/e2e/aws_test.go
Labels: approved, lgtm, size/L

#407 DEVEXP-191: CronJob to automate image registry pruning
  Dockerfile
  defaults/defaults.go
  manifests/02-rbac.yaml
  manifests/07-operator.yaml
  manifests/image-references
  pkg/client/clients.go
  pkg/client/listers.go
  pkg/operator/controller.go
  pkg/operator/status.go
  pkg/resource/generator.go
  pkg/resource/prunerclusterrolebinding.go
  pkg/resource/prunercronjob.go
  pkg/resource/prunerresource.go
  pkg/resource/prunerserviceaccount.go
  test/e2e/pruner_test.go
  test/framework/clientset.go
  test/framework/condition.go
  test/framework/pruner.go
Labels: approved, lgtm, size/XL

#445 Add support for OpenStack clouds with self-signed certificates
  pkg/resource/caconfig.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, size/M

#449 Report image pruner install status correctly.
  pkg/operator/status.go
  pkg/resource/generator.go
Labels: approved, lgtm, size/S
