Repository openshift/cluster-image-registry-operator, pull requests merged in 2020-06, with the labels that each got.

#566 Add Ricardo to OWNERS
  OWNERS
Labels: approved, lgtm

#568 Bug 1845642: Remove alert about image pruner
  manifests/09-prometheus-rules.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#570 Replace whitelist/blacklist terminology by allowlist/denylist
  test/framework/envvars.go
Labels: approved, lgtm

#567 Bug 1835770: Removing container content before deletion
  go.mod
  go.sum
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
  vendor/github.com/gophercloud/gophercloud/.travis.yml
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/auth_options.go
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/go.mod
  vendor/github.com/gophercloud/gophercloud/go.sum
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/endpoint_location.go
  vendor/github.com/gophercloud/gophercloud/openstack/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2tokens/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2tokens/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/oauth1/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/oauth1/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/oauth1/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/oauth1/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/accounts/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/accounts/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/accounts/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/accounts/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/urls.go
  vendor/github.com/gophercloud/gophercloud/pagination/http.go
  vendor/github.com/gophercloud/gophercloud/params.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/gophercloud/results.go
  vendor/github.com/gophercloud/gophercloud/service_client.go
  vendor/github.com/gophercloud/gophercloud/testhelper/convenience.go
  vendor/github.com/gophercloud/gophercloud/testhelper/http_responses.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#572 Bug 1833245: Bumping openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_20_etcd-operator_01.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/install.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/doc.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/register.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/types_conditioncheck.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
