Repository openshift/cluster-image-registry-operator, pull requests merged in 2020-08, with the labels that each got.

#587 Removed shared process namespace
  manifests/07-operator.yaml
Labels: approved, lgtm

#585 BUG 1862991: Remove storageclass from PVC creation
  pkg/operator/bootstrap.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#586 Bug 1857684: Using last finished job status and disabling retries
  pkg/operator/controllerimagepruner.go
  pkg/resource/prunercronjob.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#590 Bug 1869613: don't ignore swift errors during container deletion
  pkg/storage/swift/swift.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#589 Bug 1870513: Fix wrong usage of ErrBucketNotExist
  pkg/storage/gcs/gcs.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#591 Bug 1857782: Setting shareProcessNamespace to false
  manifests/07-operator.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#588 Bug 1833109: Refactoring for Azure Driver
  pkg/storage/azure/azure.go
  pkg/storage/azure/azure_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
