Repository openshift/cluster-image-registry-operator, pull requests merged in 2020-11, with the labels that each got.

#631 Bug 1892799: Operator should use entrypoint script
  cmd/cluster-image-registry-operator/main.go
  images/bin/entrypoint.sh
  manifests/07-operator.yaml
  test/e2e/emptydir_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#634 Bug 1893956: Make /etc/pki/ca-trust/extracted writable
  pkg/resource/podtemplatespec.go
  pkg/resource/podtemplatespec_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#637 Bug 1894677: Reduce default log level for pruner
  pkg/resource/prunercronjob.go
  pkg/resource/prunercronjob_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#639 Bug 1897520: Use mkdir -p to create ca-trust directories
  pkg/resource/podtemplatespec.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#645 Annotate manifests for single-node-developer cluster profile
  manifests/0000_90_cluster-image-registry-operator_00_servicemonitor-rbac.yaml
  manifests/0000_90_cluster-image-registry-operator_01_operand-servicemonitor.yaml
  manifests/0000_90_cluster-image-registry-operator_02_operator-servicemonitor.yaml
  manifests/01-namespace.yaml
  manifests/01-registry-credentials-request-azure.yaml
  manifests/01-registry-credentials-request-gcs.yaml
  manifests/01-registry-credentials-request-openstack.yaml
  manifests/01-registry-credentials-request.yaml
  manifests/02-rbac.yaml
  manifests/03-sa.yaml
  manifests/04-ca-trusted.yaml
  manifests/05-ca-rbac.yaml
  manifests/06-ca-serviceaccount.yaml
  manifests/07-operator-service.yaml
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
  manifests/09-prometheus-rules.yaml
Labels: approved, lgtm
