Repository openshift/cluster-image-registry-operator, pull requests merged in 2020-05, with the labels that each got.

#518 Bug 1809005: Always set node selector kubernetes.io/os to linux
  pkg/resource/podtemplatespec.go
Labels: approved, bugzilla/valid-bug, lgtm

#542 Bug 1823676: Update relatedObjects and add operator starter (refactoring)
  cmd/cluster-image-registry-operator/main.go
  pkg/client/clients.go
  pkg/operator/clusteroperator.go
  pkg/operator/controller.go
  pkg/operator/controllerimagepruner.go
  pkg/operator/starter.go
  pkg/resource/caconfig.go
  pkg/resource/clusteroperator.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/generatorimagepruner.go
  pkg/resource/nodecadaemon.go
  pkg/resource/prunerclusterrolebinding.go
  pkg/resource/prunercronjob.go
  pkg/resource/prunerserviceaccount.go
  pkg/resource/pullsecret.go
  pkg/resource/resource.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
  pkg/resource/serviceca.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#536 Bug 1810563: bootstrap HA configuration
  pkg/operator/bootstrap.go
  pkg/storage/storage.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#545 Bug 1831088: removing verify-sec / gosec
  Makefile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#547 Bug 1813894: Stop using service ca from service account token
  pkg/client/listers.go
  pkg/operator/controllerimagepruner.go
  pkg/resource/generator.go
  pkg/resource/generatorimagepruner.go
  pkg/resource/prunercronjob.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#552 Bug 1700206: Use sentence case for error messages
  pkg/operator/status.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#553 Bug 1834243: Refactored GCS day 2 e2e tests
  test/e2e/gcs_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#551 Bug 1817119: Remove retries from azure client
  pkg/storage/azure/azure.go
  test/e2e/configuration_test.go
  test/framework/imageregistry.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#556 Bug 1836796: Fix ca bundle for image-pruner
  pkg/resource/prunercronjob.go
  test/e2e/pruner_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#554 Bug 1827075: Drain GCS buckets before removal
  pkg/storage/gcs/gcs.go
  test/e2e/removed_test.go
  test/framework/clientset.go
  test/framework/logs.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/build.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/build_client.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/buildconfig.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image_client.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagesignature.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestream.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamimage.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamimport.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreammapping.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamtag.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagetag.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#558 Bug 1838977: virtualHostedStyle should be false for public regions
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#557 Bug 1823676: Aggregate conditions from all controllers
  pkg/client/fake/fixtures.go
  pkg/client/listers.go
  pkg/client/operatorclient.go
  pkg/operator/clusteroperator.go
  pkg/operator/controller.go
  pkg/operator/controllerimagepruner.go
  pkg/operator/imageconfig.go
  pkg/operator/imageregistrycertificates.go
  pkg/operator/nodecadaemon.go
  pkg/operator/starter.go
  pkg/operator/status.go
  pkg/resource/clusteroperator.go
  pkg/resource/clusteroperator_test.go
  test/e2e/pruner_test.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#560 Bug 1835004: Use keepYoungerThanDuration
  go.mod
  go.sum
  pkg/resource/prunercronjob.go
  pkg/resource/prunercronjob_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#562 Bug 1838960: Change region parameters only when region is not configured
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#561 Bug 1828608: Removing ImageRegistryRemoved alert
  manifests/09-prometheus-rules.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#564 Bug 1836753: Use release-4.3 api
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#565 Bug 1841080: Increasing default startingDeadlineSeconds
  pkg/resource/prunercronjob.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
