Repository openshift/cluster-image-registry-operator, pull requests merged in 2020-02, with the labels that each got.

#454 [release-4.3] Bug 1796822: Support deployment on OpenStack with self-signed certificate
  pkg/resource/caconfig.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#446 Bug 1791934: independent controller for clusteroperators
  pkg/operator/bootstrap.go
  pkg/operator/clusteroperator.go
  pkg/operator/controller.go
  pkg/resource/clusteroperator.go
  pkg/resource/clusteroperator_test.go
  pkg/resource/generator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#457 Bug 1801474: nodeca daemon should tolerate all taints
  bindata/nodecadaemon.yaml
  pkg/assets/bindata.go
  pkg/resource/nodecadaemon_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#460 Bug 1803970: Creating ClusterOperator resource on ErrStorageNotConfigured
  pkg/operator/clusteroperator.go
  test/e2e/baremetal_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#463 Bug 1785534: fix regression
  pkg/storage/swift/swift.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#466 DEVEXP-515 - Mounting install pull secrets on image registry.
  defaults/defaults.go
  pkg/resource/generator.go
  pkg/resource/podtemplatespec.go
  pkg/resource/podtemplatespec_test.go
  pkg/resource/pullsecret.go
Labels: approved, lgtm, size/L

#459 Bug 1806686: Image pruner updates: Controller / Prune Registry
  cmd/cluster-image-registry-operator/main.go
  pkg/client/listers.go
  pkg/operator/controller.go
  pkg/operator/controllerimagepruner.go
  pkg/operator/status.go
  pkg/resource/generator.go
  pkg/resource/generatorimagepruner.go
  pkg/resource/prunercronjob.go
  pkg/resource/prunerresource.go
  test/e2e/pruner_test.go
  test/framework/util.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#470 Bug 1776665: Remove watch for KubeSystem ConfigMaps
  pkg/client/fake/fixtures.go
  pkg/client/listers.go
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/storage/azure/azure.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  test/e2e/gcs_test.go
  test/framework/mock/listers/listers.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#474 Bug 1785534: remove storage status when storage is removed
  pkg/resource/generator.go
  pkg/storage/storage.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
