Repository openshift/cluster-image-registry-operator, pull requests merged in 2020-07, with the labels that each got.

#569 Bug 1846263: Avoiding bootstrap failure on unavailable swift
  pkg/operator/bootstrap.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#577 Implementing unit tests for GetConfig
  pkg/storage/azure/azure.go
  pkg/storage/azure/azure_test.go
Labels: approved, lgtm

#578 IR-91: Support Azure CloudName
  README.md
  go.mod
  go.sum
  pkg/storage/azure/azure.go
  pkg/storage/azure/azure_test.go
  pkg/storage/storage.go
  vendor/github.com/Azure/go-autorest/autorest/mocks/LICENSE
  vendor/github.com/Azure/go-autorest/autorest/mocks/go.mod
  vendor/github.com/Azure/go-autorest/autorest/mocks/go.sum
  vendor/github.com/Azure/go-autorest/autorest/mocks/go_mod_tidy_hack.go
  vendor/github.com/Azure/go-autorest/autorest/mocks/helpers.go
  vendor/github.com/Azure/go-autorest/autorest/mocks/mocks.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#580 Bug 1858772: Fix TestPodAffinityConfiguration flake
  test/e2e/configuration_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#583 Enable registry by default for ovirt
  pkg/storage/storage.go
Labels: approved, lgtm
