Repository openshift/cluster-image-registry-operator, pull requests merged in 2020-03, with the labels that each got.

#462 Bug 1798618: Make driver on Mutators optional.
  pkg/operator/controller.go
  pkg/operator/status.go
  pkg/resource/caconfig.go
  pkg/resource/clusterrole.go
  pkg/resource/clusterrolebinding.go
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/resource/serviceaccount.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#479 Bug 1809467: Making storage driver optional on Mutators.
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/secret.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#481 Re-grouping and re-ordering go imports
  cmd/cluster-image-registry-operator/main.go
  pkg/client/fake/fixtures.go
  pkg/metrics/server.go
  pkg/operator/bootstrap.go
  pkg/operator/complete.go
  pkg/operator/finalizer.go
  pkg/operator/status.go
  pkg/resource/caconfig.go
  pkg/resource/clusteroperator_test.go
  pkg/resource/deployment.go
  pkg/resource/generator.go
  pkg/resource/generatorimagepruner.go
  pkg/resource/imageconfig.go
  pkg/resource/podtemplatespec.go
  pkg/resource/podtemplatespec_test.go
  pkg/resource/prunercronjob.go
  pkg/resource/pullsecret.go
  pkg/resource/route.go
  pkg/resource/secret.go
  pkg/resource/service.go
  pkg/storage/storage.go
  pkg/storage/swift/swift_test.go
  pkg/storage/util/util.go
  pkg/storage/util/util_test.go
  test/e2e/aws_test.go
  test/e2e/baremetal_test.go
  test/e2e/configuration_test.go
  test/e2e/emptydir_test.go
  test/e2e/failing_test.go
  test/e2e/gcs_test.go
  test/e2e/graceful_shutdown_test.go
  test/e2e/imageconfig_test.go
  test/e2e/managementstate_test.go
  test/e2e/pruner_test.go
  test/e2e/pvc_test.go
  test/e2e/readonly_test.go
  test/e2e/recreate_deployment_test.go
  test/framework/clientset.go
  test/framework/condition.go
  test/framework/configmap.go
  test/framework/daemonset.go
  test/framework/deployment.go
  test/framework/hostname.go
  test/framework/imageregistry.go
  test/framework/mock/listers/listers.go
  test/framework/mock/listers/secrets.go
  test/framework/proxy.go
  test/framework/pruner.go
  test/framework/route.go
Labels: approved, lgtm, size/L

#465 Bug 1806158: Ignore Swift backend if the user doesn't have required permissions
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#482 Bug 1810317: bootstrap HA configuration
  pkg/operator/bootstrap.go
  pkg/resource/generator.go
  pkg/storage/storage.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#475 [release-4.3] Bug 1808426: backport removing kubesystem configmap watch
  pkg/client/fake/fixtures.go
  pkg/client/listers.go
  pkg/operator/controller.go
  pkg/storage/azure/azure.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  test/e2e/gcs_test.go
  test/framework/mock/listers/listers.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#487 Bug 1811846: restore default value for replicas on baremetal/ovirt/vsphere
  pkg/storage/storage.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#489 Add controller for node-ca daemonset
  pkg/operator/controller.go
  pkg/operator/nodecadaemon.go
  pkg/resource/clusteroperator.go
  pkg/resource/generator.go
  pkg/resource/nodecadaemon.go
  pkg/resource/nodecadaemon_test.go
  test/e2e/nodecadaemon_test.go
Labels: approved, lgtm, size/L

#477 [release-4.2] Bug 1808505: only process install config changes to configmaps in the…
  pkg/operator/controller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#492 Bump(*): openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#496 Bug 1776665: Ignore most kube system events
  go.mod
  pkg/client/fake/fixtures.go
  pkg/client/listers.go
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/storage/azure/azure.go
  pkg/storage/gcs/gcs.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  test/e2e/gcs_test.go
  test/framework/mock/listers/listers.go
  vendor/github.com/openshift/installer/LICENSE
  vendor/github.com/openshift/installer/NOTICE
  vendor/github.com/openshift/installer/pkg/ipnet/ipnet.go
  vendor/github.com/openshift/installer/pkg/types/aws/doc.go
  vendor/github.com/openshift/installer/pkg/types/aws/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/aws/metadata.go
  vendor/github.com/openshift/installer/pkg/types/aws/platform.go
  vendor/github.com/openshift/installer/pkg/types/azure/doc.go
  vendor/github.com/openshift/installer/pkg/types/azure/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/azure/metadata.go
  vendor/github.com/openshift/installer/pkg/types/azure/platform.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/OWNERS
  vendor/github.com/openshift/installer/pkg/types/baremetal/doc.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/metadata.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/platform.go
  vendor/github.com/openshift/installer/pkg/types/clustermetadata.go
  vendor/github.com/openshift/installer/pkg/types/doc.go
  vendor/github.com/openshift/installer/pkg/types/gcp/clouduid.go
  vendor/github.com/openshift/installer/pkg/types/gcp/doc.go
  vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/gcp/metadata.go
  vendor/github.com/openshift/installer/pkg/types/gcp/platform.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/installconfig_libvirt.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/OWNERS
  vendor/github.com/openshift/installer/pkg/types/libvirt/doc.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/metadata.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/network.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/platform.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/none/doc.go
  vendor/github.com/openshift/installer/pkg/types/none/platform.go
  vendor/github.com/openshift/installer/pkg/types/openstack/OWNERS
  vendor/github.com/openshift/installer/pkg/types/openstack/doc.go
  vendor/github.com/openshift/installer/pkg/types/openstack/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/openstack/metadata.go
  vendor/github.com/openshift/installer/pkg/types/openstack/platform.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/OWNERS
  vendor/github.com/openshift/installer/pkg/types/vsphere/doc.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/platform.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#499 Verify code with golangci-lint
  .gitignore
  Makefile
  cmd/cluster-image-registry-operator/main.go
  pkg/client/fake/fixtures.go
  pkg/metrics/server_test.go
  pkg/operator/bootstrap.go
  pkg/operator/controllerimagepruner.go
  pkg/operator/status.go
  pkg/resource/prunercronjob.go
  pkg/storage/azure/azure.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  test/e2e/gcs_test.go
  test/e2e/imageconfig_test.go
  test/e2e/pruner_test.go
  test/framework/cvo.go
  test/framework/hostname.go
Labels: approved, lgtm

#458 TestEnv wrapper around testing.T
  pkg/operator/status.go
  test/e2e/aws_test.go
  test/e2e/baremetal_test.go
  test/e2e/configuration_test.go
  test/e2e/emptydir_test.go
  test/e2e/failing_test.go
  test/e2e/gcs_test.go
  test/e2e/graceful_shutdown_test.go
  test/e2e/imageconfig_test.go
  test/e2e/main_test.go
  test/e2e/managementstate_test.go
  test/e2e/nodecadaemon_test.go
  test/e2e/pruner_test.go
  test/e2e/pvc_test.go
  test/e2e/readonly_test.go
  test/e2e/recreate_deployment_test.go
  test/framework/condition.go
  test/framework/configmap.go
  test/framework/cvo.go
  test/framework/daemonset.go
  test/framework/envvars.go
  test/framework/hostname.go
  test/framework/imageregistry.go
  test/framework/intrastructure.go
  test/framework/jsonpatch.go
  test/framework/operator.go
  test/framework/proxy.go
  test/framework/route.go
  test/framework/testenv.go
Labels: approved, lgtm, size/XXL
