Repository openshift/cluster-image-registry-operator, pull requests merged in 2020-10, with the labels that each got.

#616 Bug 1880314: Fix bug in reflector not recovering from "Too large resource version"
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/parser.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#622 Cleanup: Use constants if possible
  pkg/defaults/defaults.go
  pkg/operator/controller.go
  pkg/storage/util/util.go
Labels: approved, lgtm

#621 Updating ose-cluster-image-registry-operator builder & base images to be consistent with ART
  Dockerfile
Labels: approved, lgtm

#624 Bug 1886849: panic during creation of Azure storage container
  pkg/storage/azure/azure.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#626 Bug 1885856: Creating prometheus record rule for v1 imports
  manifests/09-prometheus-rules.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#628 Bug 1888118: Add memory request for operator
  manifests/07-operator.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#625 Bug 1850465: Keep node-ca daemonset in-sync with reference version
  pkg/client/operatorclient.go
  pkg/operator/nodecadaemon.go
  pkg/resource/nodecadaemon.go
  pkg/resource/nodecadaemon_test.go
  test/e2e/nodecadaemon_test.go
Labels: approved, lgtm

#608 Bug 1887737: Skip TestImageRegistryRemovedWithImages on vSphere
  test/e2e/removed_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#629 add current profile annotations to CVO manifests
  manifests/0000_90_cluster-image-registry-operator_00_servicemonitor-rbac.yaml
  manifests/0000_90_cluster-image-registry-operator_01_operand-servicemonitor.yaml
  manifests/0000_90_cluster-image-registry-operator_02_operator-servicemonitor.yaml
  manifests/01-namespace.yaml
  manifests/01-registry-credentials-request-azure.yaml
  manifests/01-registry-credentials-request-gcs.yaml
  manifests/01-registry-credentials-request-openstack.yaml
  manifests/01-registry-credentials-request.yaml
  manifests/02-rbac.yaml
  manifests/03-sa.yaml
  manifests/04-ca-trusted.yaml
  manifests/05-ca-rbac.yaml
  manifests/06-ca-serviceaccount.yaml
  manifests/07-operator-service.yaml
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
  manifests/09-prometheus-rules.yaml
Labels: approved, lgtm

#627 Bug 1887010: Make pruner always aware of registry name
  pkg/client/listers.go
  pkg/operator/controllerimagepruner.go
  pkg/operator/starter.go
  pkg/resource/generatorimagepruner.go
  pkg/resource/prunercronjob.go
  test/e2e/pruner_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
