Repository openshift/cluster-image-registry-operator, pull requests merged in 2021-03, with the labels that each got.

#665 Bug 1929654: Creating StorageAccount V2 instead of V1
  pkg/storage/azure/azure.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#667 Bug 1933180: Allow more node-ca unavailable replicas during upgrade
  bindata/nodecadaemon.yaml
  pkg/assets/bindata.go
  pkg/operator/nodecadaemon.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#664 Add service account names to credentials request manifest
  manifests/01-registry-credentials-request.yaml
Labels: approved, lgtm

#671 Bug 1939731: Add PodDisruptionBudget for image-registry
  manifests/02-rbac.yaml
  pkg/client/listers.go
  pkg/operator/controller.go
  pkg/resource/generator.go
  pkg/resource/poddisruptionbudget.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
