Repository openshift/cluster-image-registry-operator, pull requests merged in 2021-06, with the labels that each got.

#674 Bug 1937464: Swift: Do not modify driver config
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#691 Bug 1966459: Use batch/v1 and policy/v1
  pkg/client/clients.go
  pkg/client/listers.go
  pkg/operator/controller.go
  pkg/operator/controllerimagepruner.go
  pkg/operator/status.go
  pkg/resource/generator.go
  pkg/resource/poddisruptionbudget.go
  pkg/resource/prunercronjob.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, qe-approved

#690 [release-4.6] Bug 1959563: Using http.DefaultTransport timeouts
  pkg/storage/s3/s3.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#668 Bug 1918376: Allowing system:registry to list ICSP rules
  pkg/resource/clusterrole.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#694 Bug 1973318: Properly set custom tolerations
  pkg/resource/prunercronjob.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#700 Bug 1974651: Remove :apiserver_v1_image_imports:sum
  manifests/09-prometheus-rules.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, qe-approved

#699 Bug 1939842: Get AWS STS endpoint from serviceEndpoints
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  test/e2e/aws_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, qe-approved
