Repository openshift/cluster-image-registry-operator, pull requests merged in 2021-04, with the labels that each got.

#676 Bug 1944762: Allow disruptions when operand has only one replica
  pkg/resource/generator.go
  pkg/resource/poddisruptionbudget.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#669 Bug 1923811: Report ready replicas
  pkg/operator/status.go
  test/e2e/aws_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#643 Bug 1948714: IBM Cloud manifest profile patch
  Makefile
  go.mod
  go.sum
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator.yaml
  profile-patches/ibm-cloud-managed/07-operator.yaml-patch
  tools.go
  vendor/github.com/openshift/build-machinery-go/make/lib/doc.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/tmp.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/release.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#677 Add management workload annotations
  bindata/nodecadaemon.yaml
  manifests/01-namespace.yaml
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator.yaml
  pkg/assets/bindata.go
  pkg/defaults/defaults.go
  pkg/resource/podtemplatespec.go
Labels: approved, bugzilla/valid-bug, lgtm
