Repository openshift/cluster-image-registry-operator, pull requests merged in 2021-01, with the labels that each got.

#648 Bug 1902091: Using http.DefaultTransport timeouts
  pkg/storage/s3/s3.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#653 Bug 1907202: Sync status to spec with regards to Swift config
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#650 Bug 1915041: add ListMultipartUploadParts permission
  manifests/01-registry-credentials-request.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#658 Bug 1914407: Explicitly set node-ca runAsUser and runAsGroup
  bindata/nodecadaemon.yaml
  pkg/assets/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
