Repository openshift/cluster-image-registry-operator, pull requests merged in 2021-02, with the labels that each got.

#640 Bug 1921909: build and use AWS config file for operator and operand
  manifests/01-registry-credentials-request.yaml
  manifests/07-operator.yaml
  pkg/resource/deployment_test.go
  pkg/resource/podtemplatespec.go
  pkg/resource/podtemplatespec_test.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  test/e2e/aws_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, docs-approved, lgtm, px-approved, qe-approved

#660 Bug 1902076: Checking for route status
  pkg/operator/controller.go
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#656 [release-4.5] Bug 1916859: Sync status to spec with regards to Swift config
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
