Repository openshift/cluster-image-registry-operator, pull requests merged in 2022-01, with the labels that each got.

#738 Cleanup go.mod
  go.mod
Labels: approved, lgtm, docs-approved, px-approved, qe-approved

#739 IR-227: Remove fallback from platformStatus to installer config
  go.mod
  go.sum
  pkg/client/fake/fixtures.go
  pkg/client/listers.go
  pkg/operator/controller.go
  pkg/storage/util/util.go
  test/framework/mock/listers/listers.go
  vendor/github.com/openshift/installer/LICENSE
  vendor/github.com/openshift/installer/NOTICE
  vendor/github.com/openshift/installer/pkg/ipnet/ipnet.go
  vendor/github.com/openshift/installer/pkg/types/aws/doc.go
  vendor/github.com/openshift/installer/pkg/types/aws/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/aws/metadata.go
  vendor/github.com/openshift/installer/pkg/types/aws/platform.go
  vendor/github.com/openshift/installer/pkg/types/azure/doc.go
  vendor/github.com/openshift/installer/pkg/types/azure/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/azure/metadata.go
  vendor/github.com/openshift/installer/pkg/types/azure/platform.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/OWNERS
  vendor/github.com/openshift/installer/pkg/types/baremetal/doc.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/metadata.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/platform.go
  vendor/github.com/openshift/installer/pkg/types/clustermetadata.go
  vendor/github.com/openshift/installer/pkg/types/doc.go
  vendor/github.com/openshift/installer/pkg/types/gcp/clouduid.go
  vendor/github.com/openshift/installer/pkg/types/gcp/doc.go
  vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/gcp/metadata.go
  vendor/github.com/openshift/installer/pkg/types/gcp/platform.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/installconfig_libvirt.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/OWNERS
  vendor/github.com/openshift/installer/pkg/types/libvirt/doc.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/metadata.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/network.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/platform.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/none/doc.go
  vendor/github.com/openshift/installer/pkg/types/none/platform.go
  vendor/github.com/openshift/installer/pkg/types/openstack/OWNERS
  vendor/github.com/openshift/installer/pkg/types/openstack/doc.go
  vendor/github.com/openshift/installer/pkg/types/openstack/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/openstack/metadata.go
  vendor/github.com/openshift/installer/pkg/types/openstack/platform.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/OWNERS
  vendor/github.com/openshift/installer/pkg/types/vsphere/doc.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/platform.go
  vendor/modules.txt
Labels: approved, lgtm, docs-approved, px-approved, qe-approved

#743 Bug 2039170: Change log level for debug messages
  pkg/operator/controller.go
  pkg/operator/controllerimagepruner.go
  pkg/resource/caconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#742 Bug 2015800: fix(ibmcos): Resource key validation + update status granularly
  pkg/storage/ibmcos/ibmcos.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, qe-approved

#745 Bug 2048186: Fix panic in finalizer handler
  .gitignore
  pkg/operator/controller.go
  pkg/operator/finalizer.go
  test/e2e/aws_test.go
  test/framework/clusteroperators.go
  test/framework/imageregistry.go
  test/framework/logs.go
  test/framework/operator.go
  test/framework/pods.go
  test/framework/testenv.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
