Repository openshift/cluster-image-registry-operator, pull requests merged in 2022-11, with the labels that each got.

#809 add myself to OWNERS
  OWNERS
Labels: approved, lgtm, docs-approved, px-approved, qe-approved

#808 OCPBUGS-2941: Bump gophercloud
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/severity-moderate, jira/valid-bug

#814 OCPBUGS-3974: check for nil pointer before dereferencing
  pkg/operator/status.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/severity-low, jira/valid-bug

#812 OCPBUGS-3175: Bump gophercloud
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, jira/severity-moderate, jira/valid-bug

#818 hack/test-go.sh: generate coverage reports
  hack/test-go.sh
Labels: approved, lgtm, docs-approved, px-approved, qe-approved

#820 Add config for golangci-lint and fix errors
  .golangci.yaml
  Makefile
  cmd/cluster-image-registry-operator/main.go
  pkg/client/operatorclient.go
  pkg/metrics/server_test.go
  pkg/operator/metrics.go
  pkg/operator/starter.go
  pkg/resource/dependencies.go
  pkg/resource/deployment_test.go
  pkg/resource/podtemplatespec_test.go
  pkg/resource/strategy/override_test.go
  pkg/signals/signal.go
  pkg/storage/azure/azure.go
  pkg/storage/azure/azure_test.go
  pkg/storage/ibmcos/ibmcos.go
  pkg/storage/oss/oss.go
  pkg/storage/oss/oss_test.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
  pkg/storage/util/util.go
  pkg/version/version.go
  test/e2e/aws_test.go
  test/e2e/configuration_test.go
  test/e2e/graceful_shutdown_test.go
  test/e2e/leaderelection_test.go
  test/e2e/removed_test.go
  test/framework/condition.go
  test/framework/framework.go
  test/framework/imageregistry.go
  test/framework/logs.go
  test/framework/mock/listers/configmaps.go
  test/framework/mock/listers/secrets.go
  test/framework/operator.go
  test/framework/secret.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved
