Repository openshift/cluster-image-registry-operator, pull requests merged in 2022-05, with the labels that each got.

#770 Bug 2007611: Merge S3 CA bundle with system CA bundle
  pkg/storage/s3/s3.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#764 Bug 2065224: Fix cloudfront middleware configuration
  pkg/resource/podtemplatespec_test.go
  pkg/storage/s3/s3.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#772 Bug 2009352: IR-120: Add prometheus rules for image stream tags rules
  manifests/09-prometheus-rules-imagestreams.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#776 Bug 2082492: IBMCloud: Add admin permissions to CR
  manifests/01-registry-credentials-request-ibmcos.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, qe-approved

#769 Bug 2009352: IR-253: add prometheus rules for image registry operations metrics
  docs/README.md
  docs/metrics.md
  manifests/09-prometheus-rules-imagestreams.yaml
  manifests/09-prometheus-rules-registry-operations.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, docs-approved, px-approved

#781 Add reviewers
  OWNERS
Labels: approved, lgtm, docs-approved, px-approved, qe-approved

#780 Bug 2084514: Fix cloudfront middleware configuration
  pkg/resource/podtemplatespec_test.go
  pkg/storage/s3/s3.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#783 Bump golangci-lint
  Makefile
Labels: approved, lgtm, docs-approved, px-approved, qe-approved
