Repository openshift/cluster-image-registry-operator, pull requests merged in 2023-02, with the labels that each got.

#823 IR-270: allow registry to create image objects
  pkg/resource/clusterrole.go
  pkg/resource/clusterrole_test.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved

#838 add myself to OWNERS
  OWNERS
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed

#832 [release-4.10] OCPBUGS-5974: swift: Retry connecting to OpenStack
  Makefile
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#839 OCPBUGS-7371: swift: Retry connecting to OpenStack
  Makefile
  pkg/storage/storage.go
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#844 OCPBUGS-6621: bump aws-sdk-go
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/credentials/processcreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/service/s3/platform_handlers_go1.6.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#843 MULTIARCH-3212: Use IBM COS as storage backend for PowerVS
  go.mod
  go.sum
  manifests/01-registry-credentials-request-powervs.yaml
  pkg/storage/ibmcos/ibmcos.go
  pkg/storage/ibmcos/powervs_regions.go
  pkg/storage/storage.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference
