Repository openshift/cluster-image-registry-operator, pull requests merged in 2023-08, with the labels that each got.

#872 CFE-682 : Add user defined labels to the GCP buckets created
  pkg/storage/gcs/gcp_labels_tags.go
  pkg/storage/gcs/gcs.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved

#890 IR-363: Update Azure Credentials Request manifest of the Cluster Image Registry Operator to use new API field for requesting permissions
  manifests/01-registry-credentials-request-azure.yaml
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#867 IR-373: remove node-ca daemon
  bindata/assets.go
  bindata/nodecadaemon.yaml
  pkg/operator/nodecadaemon.go
  pkg/resource/nodecadaemon.go
  pkg/resource/nodecadaemon_test.go
  test/e2e/aws_test.go
  test/e2e/graceful_shutdown_test.go
  test/e2e/nodecadaemon_test.go
  test/e2e/pruner_test.go
  test/framework/daemonset.go
  test/framework/imageregistry.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#899 TRT-1193: Revert "IR-373: remove node-ca daemon"
  bindata/assets.go
  bindata/nodecadaemon.yaml
  pkg/operator/nodecadaemon.go
  pkg/resource/nodecadaemon.go
  pkg/resource/nodecadaemon_test.go
  test/e2e/aws_test.go
  test/e2e/graceful_shutdown_test.go
  test/e2e/nodecadaemon_test.go
  test/e2e/pruner_test.go
  test/framework/daemonset.go
  test/framework/imageregistry.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#891 OCPBUGS-17882: Add rbac permission IDMS, ITMS
  pkg/resource/clusterrole.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-bug, jira/valid-reference

#856 OCPVE-632: add capability annotations to manifests
  manifests/0000_90_cluster-image-registry-operator_00_servicemonitor-rbac.yaml
  manifests/0000_90_cluster-image-registry-operator_01_operand-servicemonitor.yaml
  manifests/0000_90_cluster-image-registry-operator_02_operator-servicemonitor.yaml
  manifests/01-namespace.yaml
  manifests/01-registry-credentials-request-alibaba.yaml
  manifests/01-registry-credentials-request-azure.yaml
  manifests/01-registry-credentials-request-gcs.yaml
  manifests/01-registry-credentials-request-ibmcos.yaml
  manifests/01-registry-credentials-request-openstack.yaml
  manifests/01-registry-credentials-request-powervs.yaml
  manifests/01-registry-credentials-request.yaml
  manifests/02-rbac.yaml
  manifests/03-sa.yaml
  manifests/04-ca-trusted.yaml
  manifests/05-ca-rbac.yaml
  manifests/06-ca-serviceaccount.yaml
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator-service.yaml
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
  manifests/09-prometheus-rules-imagestreams.yaml
  manifests/09-prometheus-rules-registry-operations.yaml
  manifests/09-prometheus-rules.yaml
  manifests/image-references
  profile-patches/ibm-cloud-managed/07-operator.yaml-patch
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only
