Repository openshift/cluster-image-registry-operator, pull requests merged in 2024-05, with the labels that each got.

#1030 OCPBUGS-33172: azurepathfix: check if platform status is nil before accessing it
  pkg/operator/azurepathfixcontroller.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1029 OCPBUGS-33149: azure-path-fix: get client secret from k8s secret
  pkg/resource/azurepathfixjob.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, jira/valid-bug, jira/valid-reference

#1028 OCPBUGS-32710: pkg/storage/s3: use force path style in favour of virtual hosted style config
  pkg/resource/podtemplatespec_test.go
  pkg/storage/ibmcos/ibmcos.go
  pkg/storage/ibmcos/ibmcos_test.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1026 OCPBUGS-34399: Exposing chunksize variable to utilize docker registry config
  manifests/02-rbac.yaml
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator.yaml
  pkg/operator/azurepathfixcontroller.go
  pkg/operator/controller.go
  pkg/operator/imageregistrycertificates.go
  pkg/operator/starter.go
  pkg/resource/caconfig.go
  pkg/resource/generator.go
  pkg/resource/imageregistryca.go
  pkg/resource/podtemplatespec_test.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  pkg/storage/storage.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/github.com/openshift/library-go/pkg/certs/pem.go
  vendor/github.com/openshift/library-go/pkg/certs/util.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/config.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/label.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/inertia.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#1052 OCPBUGS-34399: Revert "Merge pull request #1026 from deepsm007/expose-chunksize"
  manifests/02-rbac.yaml
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator.yaml
  pkg/operator/azurepathfixcontroller.go
  pkg/operator/controller.go
  pkg/operator/imageregistrycertificates.go
  pkg/operator/starter.go
  pkg/resource/caconfig.go
  pkg/resource/generator.go
  pkg/resource/imageregistryca.go
  pkg/resource/podtemplatespec_test.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  pkg/storage/storage.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/github.com/openshift/library-go/pkg/certs/pem.go
  vendor/github.com/openshift/library-go/pkg/certs/util.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/config.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/label.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/inertia.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
