Repository openshift/cluster-image-registry-operator, pull requests merged in 2024-04, with the labels that each got.

#1019 NO-JIRA: remove bparees from owners
  OWNERS
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1018 [release-4.14] OCPBUGS-31857: bump aws-sdk-go from v1.44 to v1.50
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/config.go
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/awsinternal.go
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/user_agent.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ssocreds/token_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/token_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/literal_tokens.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/visitor.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/errors.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload_input.go
  vendor/github.com/aws/aws-sdk-go/service/ssooidc/api.go
  vendor/github.com/aws/aws-sdk-go/service/ssooidc/doc.go
  vendor/github.com/aws/aws-sdk-go/service/ssooidc/errors.go
  vendor/github.com/aws/aws-sdk-go/service/ssooidc/service.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1021 OCPBUGS-32328: azure-path-fix: support auth via account key (without clientID)
  cmd/move-blobs/main.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1024 OCPBUGS-32491: Power VS: Add support for Power VS endpoint overrides
  pkg/storage/ibmcos/ibmcos.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference
