Repository openshift/cluster-image-registry-operator, pull requests merged in 2024-10, with the labels that each got.

#1127 OCPBUGS-42514: azureclient: stop validating credentials when creating the client
  pkg/storage/azure/azureclient/azureclient.go
  pkg/storage/azure/azureclient/azureclient_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1130 OCPBUGS-42812: azureclient: stop validating credentials when creating the client
  pkg/storage/azure/azureclient/azureclient.go
  pkg/storage/azure/azureclient/azureclient_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1134 [release-4.16] OCPBUGS-42933: azureclient: stop validating credentials when creating the client
  pkg/storage/azure/azureclient/azureclient.go
  pkg/storage/azure/azureclient/azureclient_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1121 CFE-1129: Added AWS TAGS reconciliation
  pkg/defaults/defaults.go
  pkg/operator/awstagcontroller.go
  pkg/operator/starter.go
  pkg/storage/s3/s3.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1138 OCPBUGS-38667: pkg/operator: wait for image registry config object cache sync
  pkg/operator/azurestackcloud.go
  pkg/operator/imageconfig.go
  pkg/operator/nodecadaemon.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#1140 OCPBUGS-43508: fix proxy config and leader election test flakes
  test/e2e/configuration_test.go
  test/e2e/leaderelection_test.go
  test/framework/imageregistry.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#1131 HOSTEDCP-2019: Use Client Cert Auth for ARO HCP deployments
  go.mod
  go.sum
  pkg/storage/azure/azure.go
  pkg/storage/azure/azureclient/azureclient.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/util/interrupt/interrupt.go
  vendor/modules.txt
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1136 [release-4.15] OCPBUGS-42930: Continuous pull-secret updates / slow initialization on build01 (test platform infrastructure)
  go.mod
  pkg/operator/imageconfig.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1152 [release-4.14] OCPBUGS-44002: Continuous pull-secret updates / slow initialization on build01 (test platform infrastructure)
  go.mod
  go.sum
  pkg/operator/imageconfig.go
  vendor/golang.org/x/exp/LICENSE
  vendor/golang.org/x/exp/PATENTS
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
