Repository openshift/cluster-image-registry-operator, pull requests merged in 2024-08, with the labels that each got.

#1020 IR-467: Enable Azure MSI authentication
  pkg/storage/azure/azure.go
  pkg/storage/azure/azureclient/azureclient.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1079 Revert "IR-467: Enable Azure MSI authentication"
  pkg/storage/azure/azure.go
  pkg/storage/azure/azureclient/azureclient.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1082 IR-467: Enable MSI override for ARO HCP
  pkg/storage/azure/azure.go
  pkg/storage/azure/azureclient/azureclient.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1096 OCPBUGS-38842: pkg/resource: invoke update-ca-trust extract with --output
  pkg/resource/podtemplatespec.go
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1090 MULTIARCH-4971: Sync ImageStreamImportMode setting in the image config status
  go.mod
  go.sum
  pkg/operator/imageconfig.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/envtest-releases.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/features/util.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/modules.txt
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#1102 [release-4.16] OCPBUGS-38894: pkg/resource/azurepathfixjob: invoke update-ca-trust extract with --output
  pkg/resource/azurepathfixjob.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1105 [release-4.15] OCPBUGS-38895: pkg/resource: invoke update-ca-trust extract with --output
  pkg/resource/azurepathfixjob.go
  pkg/resource/podtemplatespec.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
