Repository openshift/cluster-image-registry-operator, pull requests merged in 2024-09, with the labels that each got.

#1115 [release-4.16] OCPBUGS-41903: pkg/operator/azurepathfixcontroller: do not sync on non-azure storage
  pkg/operator/azurepathfixcontroller.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1119 Revert "[release-4.16] OCPBUGS-41903: pkg/operator/azurepathfixcontroller: do not sync on non-azure storage"
  pkg/operator/azurepathfixcontroller.go
Labels: approved, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#1116 OCPBUGS-42004: Set the Managed Identity client ID
  pkg/storage/azure/azure.go
  pkg/storage/azure/azureclient/azureclient.go
Labels: approved, lgtm, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1120 OCPBUGS-42196: pkg/storage/azure: use cluster-api tag key to discover vnet
  pkg/storage/azure/azure.go
  pkg/storage/azure/azureclient/azureclient.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference
