Repository openshift/cluster-image-registry-operator, pull requests merged in 2024-06, with the labels that each got.

#1027 CFE-962: Refactor code to mock GCP tag service for UTs
  manifests/01-registry-credentials-request-gcs.yaml
  pkg/storage/gcs/gcp_labels_tags.go
  pkg/storage/gcs/gcp_labels_tags_test.go
  pkg/storage/gcs/gcs.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1046 OCPBUGS-33453: add SAR capability to image-registry
  manifests/02-rbac.yaml
  pkg/resource/clusterrole.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1056 OCPBUGS-34399: Update rbac for featuregate
  manifests/02-rbac.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1045 OCPBUGS-34107: Updating ose-cluster-image-registry-operator-container image to be consistent with ART for 4.17
  .ci-operator.yaml
  Dockerfile
  go.mod
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#1060 IR-471: Exposing chunksize variable to utilize docker registry config
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator.yaml
  pkg/operator/azurepathfixcontroller.go
  pkg/operator/controller.go
  pkg/operator/imageregistrycertificates.go
  pkg/operator/starter.go
  pkg/resource/caconfig.go
  pkg/resource/generator.go
  pkg/resource/imageregistryca.go
  pkg/resource/podtemplatespec_test.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  pkg/storage/storage.go
  pkg/storage/util/util.go
  test/e2e/aws_test.go
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/github.com/openshift/library-go/pkg/certs/pem.go
  vendor/github.com/openshift/library-go/pkg/certs/util.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/config.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/label.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/inertia.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/modules.txt
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1061 IR-477: pkg/operator: deactivate azure path fix job
  pkg/operator/azurepathfixcontroller.go
  pkg/resource/azurepathfixjob.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference
