Repository openshift/cluster-image-registry-operator, pull requests merged in 2024-02, with the labels that each got.

#993 OCPBUGS-28225: pkg/storage/s3: enable bucket key on encryption settings
  pkg/storage/s3/s3.go
  test/e2e/aws_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#996 NO-JIRA: Add hack/local-dev.sh
  cmd/cluster-image-registry-operator/main.go
  hack/local-dev.sh
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1006 OCPBUGS-29932: cmd/move-blobs: log and exit 1 on error instead of panic
  cmd/move-blobs/main.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
