Repository openshift/cluster-image-registry-operator, pull requests merged in 2024-07, with the labels that each got.

#1067 [release-4.15] OCPBUGS-36325: Set required-scc for openshift workloads
  bindata/nodecadaemon.yaml
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator.yaml
  pkg/resource/azurepathfixjob.go
  pkg/resource/deployment.go
  pkg/resource/prunercronjob.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1074 IR-471: Adding additional validation
  pkg/storage/s3/s3.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#1076 OCPBUGS-37207: Power VS: Check endpoints against lower case strings
  pkg/storage/ibmcos/ibmcos.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference
