Repository openshift/cluster-image-registry-operator, pull requests merged in 2025-03, with the labels that each got.

#1186 CNTRLPLANE-112: Remove ARO HCP MIv2 Authentication
  go.mod
  pkg/filewatcher/filewatcher.go
  pkg/storage/azure/azure.go
  pkg/storage/azure/azureclient/azureclient.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1194 CNTRLPLANE-112: Authenticate to Azure only once in CPO
  pkg/storage/azure/azure.go
  pkg/storage/azure/azureclient/azureclient.go
Labels: approved, lgtm, docs-approved, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1196 OCPBUGS-45409: Updating ose-cluster-image-registry-operator-container image to be consistent with ART for 4.19
  .ci-operator.yaml
  Dockerfile
  Makefile
  pkg/operator/status.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
