Repository openshift/cluster-image-registry-operator, pull requests merged in 2025-08, with the labels that each got.

#1221 OSASINFRA-3756: Add support for token-based authentication in clouds.yaml configuration file
  pkg/storage/swift/swift.go
  pkg/storage/swift/swift_test.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#1238 OCPBUGS-59734: fix(azure): resolve credential caching issues around UAMI support
  pkg/storage/azure/azure.go
  pkg/storage/azure/azure_test.go
  pkg/storage/azure/azureclient/azureclient.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-bug, jira/valid-reference

#1229 OCPBUGS-53867: Bump github.com/golang-jwt/jwt
  cmd/move-blobs/go.mod
  cmd/move-blobs/go.sum
  cmd/move-blobs/vendor/github.com/AzureAD/microsoft-authentication-library-for-go/LICENSE
  cmd/move-blobs/vendor/github.com/golang-jwt/jwt/v4/parser.go
  cmd/move-blobs/vendor/github.com/golang-jwt/jwt/v5/README.md
  cmd/move-blobs/vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  cmd/move-blobs/vendor/github.com/golang-jwt/jwt/v5/ecdsa.go
  cmd/move-blobs/vendor/github.com/golang-jwt/jwt/v5/hmac.go
  cmd/move-blobs/vendor/github.com/golang-jwt/jwt/v5/parser.go
  cmd/move-blobs/vendor/github.com/golang-jwt/jwt/v5/token.go
  cmd/move-blobs/vendor/modules.txt
  go.mod
  go.sum
  pkg/storage/ibmcos/ibmcos.go
  vendor/github.com/golang-jwt/jwt/.gitignore
  vendor/github.com/golang-jwt/jwt/LICENSE
  vendor/github.com/golang-jwt/jwt/MIGRATION_GUIDE.md
  vendor/github.com/golang-jwt/jwt/README.md
  vendor/github.com/golang-jwt/jwt/VERSION_HISTORY.md
  vendor/github.com/golang-jwt/jwt/claims.go
  vendor/github.com/golang-jwt/jwt/doc.go
  vendor/github.com/golang-jwt/jwt/ecdsa.go
  vendor/github.com/golang-jwt/jwt/ecdsa_utils.go
  vendor/github.com/golang-jwt/jwt/ed25519.go
  vendor/github.com/golang-jwt/jwt/ed25519_utils.go
  vendor/github.com/golang-jwt/jwt/errors.go
  vendor/github.com/golang-jwt/jwt/hmac.go
  vendor/github.com/golang-jwt/jwt/map_claims.go
  vendor/github.com/golang-jwt/jwt/none.go
  vendor/github.com/golang-jwt/jwt/parser.go
  vendor/github.com/golang-jwt/jwt/rsa.go
  vendor/github.com/golang-jwt/jwt/rsa_pss.go
  vendor/github.com/golang-jwt/jwt/rsa_utils.go
  vendor/github.com/golang-jwt/jwt/signing_method.go
  vendor/github.com/golang-jwt/jwt/token.go
  vendor/modules.txt
Labels: approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1236 OCPBUGS-53868: Bump github.com/golang-jwt/jwt
  go.mod
  go.sum
  pkg/storage/ibmcos/ibmcos.go
  vendor/github.com/golang-jwt/jwt/MIGRATION_GUIDE.md
  vendor/github.com/golang-jwt/jwt/README.md
  vendor/github.com/golang-jwt/jwt/claims.go
  vendor/github.com/golang-jwt/jwt/ed25519.go
  vendor/github.com/golang-jwt/jwt/errors.go
  vendor/github.com/golang-jwt/jwt/map_claims.go
  vendor/github.com/golang-jwt/jwt/parser.go
  vendor/github.com/golang-jwt/jwt/signing_method.go
  vendor/github.com/golang-jwt/jwt/token.go
  vendor/github.com/golang-jwt/jwt/v4/README.md
  vendor/github.com/golang-jwt/jwt/v4/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v4/claims.go
  vendor/github.com/golang-jwt/jwt/v4/errors.go
  vendor/github.com/golang-jwt/jwt/v4/map_claims.go
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/parser_option.go
  vendor/github.com/golang-jwt/jwt/v4/rsa_pss.go
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/github.com/golang-jwt/jwt/v5/.gitignore
  vendor/github.com/golang-jwt/jwt/v5/LICENSE
  vendor/github.com/golang-jwt/jwt/v5/MIGRATION_GUIDE.md
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/VERSION_HISTORY.md
  vendor/github.com/golang-jwt/jwt/v5/claims.go
  vendor/github.com/golang-jwt/jwt/v5/doc.go
  vendor/github.com/golang-jwt/jwt/v5/ecdsa.go
  vendor/github.com/golang-jwt/jwt/v5/ecdsa_utils.go
  vendor/github.com/golang-jwt/jwt/v5/ed25519.go
  vendor/github.com/golang-jwt/jwt/v5/ed25519_utils.go
  vendor/github.com/golang-jwt/jwt/v5/errors.go
  vendor/github.com/golang-jwt/jwt/v5/errors_go1_20.go
  vendor/github.com/golang-jwt/jwt/v5/errors_go_other.go
  vendor/github.com/golang-jwt/jwt/v5/hmac.go
  vendor/github.com/golang-jwt/jwt/v5/map_claims.go
  vendor/github.com/golang-jwt/jwt/v5/none.go
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/parser_option.go
  vendor/github.com/golang-jwt/jwt/v5/registered_claims.go
  vendor/github.com/golang-jwt/jwt/v5/rsa.go
  vendor/github.com/golang-jwt/jwt/v5/rsa_pss.go
  vendor/github.com/golang-jwt/jwt/v5/rsa_utils.go
  vendor/github.com/golang-jwt/jwt/v5/signing_method.go
  vendor/github.com/golang-jwt/jwt/v5/staticcheck.conf
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/github.com/golang-jwt/jwt/v5/token_option.go
  vendor/github.com/golang-jwt/jwt/v5/types.go
  vendor/github.com/golang-jwt/jwt/v5/validator.go
  vendor/modules.txt
Labels: approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
